import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Mobile-side representation of `zipher-cli` spending policy.
///
/// V1 scope: this lives only on the phone, in `SharedPreferences`. The user
/// drafts a policy here and exports it as TOML to drop into their server's
/// `~/.zipher/<network>/policy.toml`. V2 will pair the phone with the agent
/// over a relay and sync this automatically.
///
/// All amounts are stored in **zatoshis** (1 ZEC = 100_000_000 zats) to mirror
/// the Rust `policy::SpendingPolicy` schema 1:1. The UI does the float ↔ int
/// conversion at the edges only.
@immutable
class AgentPolicy {
  /// Max zatoshis per single transaction. 0 = unlimited.
  final int maxPerTxZat;

  /// Rolling 24h spending cap, in zatoshis. 0 = unlimited.
  final int dailyLimitZat;

  /// Minimum milliseconds between consecutive `confirm_send` calls.
  final int minSpendIntervalMs;

  /// If true, every `propose_send` must include a `context_id`.
  final bool requireContextId;

  /// Amount in zatoshis above which agent must request human approval.
  /// 0 = no approval gate.
  final int approvalThresholdZat;

  /// Address allowlist. Empty list = any destination allowed.
  final List<String> allowlist;

  const AgentPolicy({
    this.maxPerTxZat = 100000000, // 1 ZEC
    this.dailyLimitZat = 1000000000, // 10 ZEC
    this.minSpendIntervalMs = 0,
    this.requireContextId = false,
    this.approvalThresholdZat = 500000000, // 5 ZEC
    this.allowlist = const [],
  });

  /// Same defaults as `zipher-cli wallet init` (`rust/crates/cli/src/wallet.rs`).
  static const AgentPolicy defaults = AgentPolicy();

  AgentPolicy copyWith({
    int? maxPerTxZat,
    int? dailyLimitZat,
    int? minSpendIntervalMs,
    bool? requireContextId,
    int? approvalThresholdZat,
    List<String>? allowlist,
  }) {
    return AgentPolicy(
      maxPerTxZat: maxPerTxZat ?? this.maxPerTxZat,
      dailyLimitZat: dailyLimitZat ?? this.dailyLimitZat,
      minSpendIntervalMs: minSpendIntervalMs ?? this.minSpendIntervalMs,
      requireContextId: requireContextId ?? this.requireContextId,
      approvalThresholdZat: approvalThresholdZat ?? this.approvalThresholdZat,
      allowlist: allowlist ?? this.allowlist,
    );
  }

  Map<String, dynamic> toJson() => {
        'max_per_tx': maxPerTxZat,
        'daily_limit': dailyLimitZat,
        'min_spend_interval_ms': minSpendIntervalMs,
        'require_context_id': requireContextId,
        'approval_threshold': approvalThresholdZat,
        'allowlist': allowlist,
      };

  factory AgentPolicy.fromJson(Map<String, dynamic> json) {
    return AgentPolicy(
      maxPerTxZat: (json['max_per_tx'] as num?)?.toInt() ?? 0,
      dailyLimitZat: (json['daily_limit'] as num?)?.toInt() ?? 0,
      minSpendIntervalMs:
          (json['min_spend_interval_ms'] as num?)?.toInt() ?? 0,
      requireContextId: json['require_context_id'] as bool? ?? false,
      approvalThresholdZat:
          (json['approval_threshold'] as num?)?.toInt() ?? 0,
      allowlist: (json['allowlist'] as List?)?.cast<String>() ?? const [],
    );
  }

  /// Render the policy as the TOML the engine expects on disk at
  /// `~/.zipher/<network>/policy.toml`. The user can copy/paste this onto
  /// the agent host directly — that's the V1 "transport".
  String toToml() {
    final buf = StringBuffer();
    buf.writeln('# Spending policy — generated by Zipher mobile.');
    buf.writeln('# Drop this at \$HOME/.zipher/<network>/policy.toml');
    buf.writeln('# 1 ZEC = 100_000_000 zatoshis. 0 = unlimited.');
    buf.writeln();
    buf.writeln('max_per_tx = $maxPerTxZat');
    buf.writeln('daily_limit = $dailyLimitZat');
    buf.writeln('min_spend_interval_ms = $minSpendIntervalMs');
    buf.writeln('require_context_id = $requireContextId');
    buf.writeln('approval_threshold = $approvalThresholdZat');
    if (allowlist.isEmpty) {
      buf.writeln('allowlist = []');
    } else {
      buf.writeln('allowlist = [');
      for (final a in allowlist) {
        // TOML basic strings escape backslashes and quotes; addresses are
        // restricted to alnum so a plain quoted string is safe.
        buf.writeln('  "$a",');
      }
      buf.writeln(']');
    }
    return buf.toString();
  }
}

/// Singleton-style store for the local agent policy draft.
///
/// Persists to `SharedPreferences` under the key `agent_policy_json`. Calls
/// to `save` are debounced by the caller — the editor saves on field commit,
/// not on every keystroke.
class AgentPolicyStore {
  static const _prefsKey = 'agent_policy_json';

  static final AgentPolicyStore instance = AgentPolicyStore._();
  AgentPolicyStore._();

  AgentPolicy _policy = AgentPolicy.defaults;
  bool _loaded = false;

  AgentPolicy get policy => _policy;
  bool get loaded => _loaded;

  Future<void> load() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_prefsKey);
    if (raw != null && raw.isNotEmpty) {
      try {
        _policy = AgentPolicy.fromJson(jsonDecode(raw) as Map<String, dynamic>);
      } catch (_) {
        _policy = AgentPolicy.defaults;
      }
    }
    _loaded = true;
  }

  Future<void> save(AgentPolicy next) async {
    _policy = next;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, jsonEncode(next.toJson()));
  }

  Future<void> reset() async {
    await save(AgentPolicy.defaults);
  }
}
