// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/engine_api.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<EngineSyncEvent> dco_decode_StreamSink_engine_sync_event_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressInfo dco_decode_address_info(dynamic raw);

  @protected
  AddressValidation dco_decode_address_validation(dynamic raw);

  @protected
  AutoMigrationStatus dco_decode_auto_migration_status(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ChainType dco_decode_chain_type(dynamic raw);

  @protected
  EngineDelegationResult dco_decode_engine_delegation_result(dynamic raw);

  @protected
  EngineEncryptedShare dco_decode_engine_encrypted_share(dynamic raw);

  @protected
  EngineFrostActionSignature dco_decode_engine_frost_action_signature(
      dynamic raw);

  @protected
  EngineFrostAggregateResult dco_decode_engine_frost_aggregate_result(
      dynamic raw);

  @protected
  EngineFrostDkgCompleteResult dco_decode_engine_frost_dkg_complete_result(
      dynamic raw);

  @protected
  EngineFrostDkgRound1Result dco_decode_engine_frost_dkg_round_1_result(
      dynamic raw);

  @protected
  EngineFrostDkgRound2Result dco_decode_engine_frost_dkg_round_2_result(
      dynamic raw);

  @protected
  EngineFrostParticipantPackage dco_decode_engine_frost_participant_package(
      dynamic raw);

  @protected
  EngineFrostPcztActionRequest dco_decode_engine_frost_pczt_action_request(
      dynamic raw);

  @protected
  EngineFrostPcztSigningRequest dco_decode_engine_frost_pczt_signing_request(
      dynamic raw);

  @protected
  EngineFrostRandomizerResult dco_decode_engine_frost_randomizer_result(
      dynamic raw);

  @protected
  EngineFrostRelayIdentity dco_decode_engine_frost_relay_identity(dynamic raw);

  @protected
  EngineFrostRelayLoginProof dco_decode_engine_frost_relay_login_proof(
      dynamic raw);

  @protected
  EngineFrostSigningRound1Result dco_decode_engine_frost_signing_round_1_result(
      dynamic raw);

  @protected
  EngineFrostWalletView dco_decode_engine_frost_wallet_view(dynamic raw);

  @protected
  EngineInvoice dco_decode_engine_invoice(dynamic raw);

  @protected
  EngineMultiChainAddresses dco_decode_engine_multi_chain_addresses(
      dynamic raw);

  @protected
  EngineSharePayload dco_decode_engine_share_payload(dynamic raw);

  @protected
  EngineSyncEvent dco_decode_engine_sync_event(dynamic raw);

  @protected
  EngineSyncProgress dco_decode_engine_sync_progress(dynamic raw);

  @protected
  EngineTransactionRecord dco_decode_engine_transaction_record(dynamic raw);

  @protected
  EngineVanWitness dco_decode_engine_van_witness(dynamic raw);

  @protected
  EngineVoteCommitment dco_decode_engine_vote_commitment(dynamic raw);

  @protected
  EngineVotingEligibility dco_decode_engine_voting_eligibility(dynamic raw);

  @protected
  EngineVotingHotkey dco_decode_engine_voting_hotkey(dynamic raw);

  @protected
  EvmFees dco_decode_evm_fees(dynamic raw);

  @protected
  EvmReceipt dco_decode_evm_receipt(dynamic raw);

  @protected
  EvmSwapExecuteResult dco_decode_evm_swap_execute_result(dynamic raw);

  @protected
  EvmSwapQuoteResult dco_decode_evm_swap_quote_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IronwoodDenomGroup dco_decode_ironwood_denom_group(dynamic raw);

  @protected
  IronwoodPlan dco_decode_ironwood_plan(dynamic raw);

  @protected
  IronwoodReconcileResult dco_decode_ironwood_reconcile_result(dynamic raw);

  @protected
  IronwoodSdkPlan dco_decode_ironwood_sdk_plan(dynamic raw);

  @protected
  IronwoodSdkProgress dco_decode_ironwood_sdk_progress(dynamic raw);

  @protected
  IronwoodTickResult dco_decode_ironwood_tick_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AddressInfo> dco_decode_list_address_info(dynamic raw);

  @protected
  List<EngineDelegationResult> dco_decode_list_engine_delegation_result(
      dynamic raw);

  @protected
  List<EngineEncryptedShare> dco_decode_list_engine_encrypted_share(
      dynamic raw);

  @protected
  List<EngineFrostActionSignature>
      dco_decode_list_engine_frost_action_signature(dynamic raw);

  @protected
  List<EngineFrostParticipantPackage>
      dco_decode_list_engine_frost_participant_package(dynamic raw);

  @protected
  List<EngineFrostPcztActionRequest>
      dco_decode_list_engine_frost_pczt_action_request(dynamic raw);

  @protected
  List<EngineSharePayload> dco_decode_list_engine_share_payload(dynamic raw);

  @protected
  List<EngineTransactionRecord> dco_decode_list_engine_transaction_record(
      dynamic raw);

  @protected
  List<EngineVanWitness> dco_decode_list_engine_van_witness(dynamic raw);

  @protected
  List<IronwoodDenomGroup> dco_decode_list_ironwood_denom_group(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<PaymentRecipient> dco_decode_list_payment_recipient(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TransactionRecord> dco_decode_list_transaction_record(dynamic raw);

  @protected
  List<ValueTransferRecord> dco_decode_list_value_transfer_record(dynamic raw);

  @protected
  MigrateTarget dco_decode_migrate_target(dynamic raw);

  @protected
  MigrationProgress dco_decode_migration_progress(dynamic raw);

  @protected
  MigrationRoundResult dco_decode_migration_round_result(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PaymentRecipient dco_decode_payment_recipient(dynamic raw);

  @protected
  PolymarketAuthResult dco_decode_polymarket_auth_result(dynamic raw);

  @protected
  ProposalResult dco_decode_proposal_result(dynamic raw);

  @protected
  SyncResultInfo dco_decode_sync_result_info(dynamic raw);

  @protected
  SyncStatusInfo dco_decode_sync_status_info(dynamic raw);

  @protected
  TransactionRecord dco_decode_transaction_record(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  ValueTransferRecord dco_decode_value_transfer_record(dynamic raw);

  @protected
  WalletBalance dco_decode_wallet_balance(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<EngineSyncEvent> sse_decode_StreamSink_engine_sync_event_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressInfo sse_decode_address_info(SseDeserializer deserializer);

  @protected
  AddressValidation sse_decode_address_validation(SseDeserializer deserializer);

  @protected
  AutoMigrationStatus sse_decode_auto_migration_status(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ChainType sse_decode_chain_type(SseDeserializer deserializer);

  @protected
  EngineDelegationResult sse_decode_engine_delegation_result(
      SseDeserializer deserializer);

  @protected
  EngineEncryptedShare sse_decode_engine_encrypted_share(
      SseDeserializer deserializer);

  @protected
  EngineFrostActionSignature sse_decode_engine_frost_action_signature(
      SseDeserializer deserializer);

  @protected
  EngineFrostAggregateResult sse_decode_engine_frost_aggregate_result(
      SseDeserializer deserializer);

  @protected
  EngineFrostDkgCompleteResult sse_decode_engine_frost_dkg_complete_result(
      SseDeserializer deserializer);

  @protected
  EngineFrostDkgRound1Result sse_decode_engine_frost_dkg_round_1_result(
      SseDeserializer deserializer);

  @protected
  EngineFrostDkgRound2Result sse_decode_engine_frost_dkg_round_2_result(
      SseDeserializer deserializer);

  @protected
  EngineFrostParticipantPackage sse_decode_engine_frost_participant_package(
      SseDeserializer deserializer);

  @protected
  EngineFrostPcztActionRequest sse_decode_engine_frost_pczt_action_request(
      SseDeserializer deserializer);

  @protected
  EngineFrostPcztSigningRequest sse_decode_engine_frost_pczt_signing_request(
      SseDeserializer deserializer);

  @protected
  EngineFrostRandomizerResult sse_decode_engine_frost_randomizer_result(
      SseDeserializer deserializer);

  @protected
  EngineFrostRelayIdentity sse_decode_engine_frost_relay_identity(
      SseDeserializer deserializer);

  @protected
  EngineFrostRelayLoginProof sse_decode_engine_frost_relay_login_proof(
      SseDeserializer deserializer);

  @protected
  EngineFrostSigningRound1Result sse_decode_engine_frost_signing_round_1_result(
      SseDeserializer deserializer);

  @protected
  EngineFrostWalletView sse_decode_engine_frost_wallet_view(
      SseDeserializer deserializer);

  @protected
  EngineInvoice sse_decode_engine_invoice(SseDeserializer deserializer);

  @protected
  EngineMultiChainAddresses sse_decode_engine_multi_chain_addresses(
      SseDeserializer deserializer);

  @protected
  EngineSharePayload sse_decode_engine_share_payload(
      SseDeserializer deserializer);

  @protected
  EngineSyncEvent sse_decode_engine_sync_event(SseDeserializer deserializer);

  @protected
  EngineSyncProgress sse_decode_engine_sync_progress(
      SseDeserializer deserializer);

  @protected
  EngineTransactionRecord sse_decode_engine_transaction_record(
      SseDeserializer deserializer);

  @protected
  EngineVanWitness sse_decode_engine_van_witness(SseDeserializer deserializer);

  @protected
  EngineVoteCommitment sse_decode_engine_vote_commitment(
      SseDeserializer deserializer);

  @protected
  EngineVotingEligibility sse_decode_engine_voting_eligibility(
      SseDeserializer deserializer);

  @protected
  EngineVotingHotkey sse_decode_engine_voting_hotkey(
      SseDeserializer deserializer);

  @protected
  EvmFees sse_decode_evm_fees(SseDeserializer deserializer);

  @protected
  EvmReceipt sse_decode_evm_receipt(SseDeserializer deserializer);

  @protected
  EvmSwapExecuteResult sse_decode_evm_swap_execute_result(
      SseDeserializer deserializer);

  @protected
  EvmSwapQuoteResult sse_decode_evm_swap_quote_result(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IronwoodDenomGroup sse_decode_ironwood_denom_group(
      SseDeserializer deserializer);

  @protected
  IronwoodPlan sse_decode_ironwood_plan(SseDeserializer deserializer);

  @protected
  IronwoodReconcileResult sse_decode_ironwood_reconcile_result(
      SseDeserializer deserializer);

  @protected
  IronwoodSdkPlan sse_decode_ironwood_sdk_plan(SseDeserializer deserializer);

  @protected
  IronwoodSdkProgress sse_decode_ironwood_sdk_progress(
      SseDeserializer deserializer);

  @protected
  IronwoodTickResult sse_decode_ironwood_tick_result(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AddressInfo> sse_decode_list_address_info(SseDeserializer deserializer);

  @protected
  List<EngineDelegationResult> sse_decode_list_engine_delegation_result(
      SseDeserializer deserializer);

  @protected
  List<EngineEncryptedShare> sse_decode_list_engine_encrypted_share(
      SseDeserializer deserializer);

  @protected
  List<EngineFrostActionSignature>
      sse_decode_list_engine_frost_action_signature(
          SseDeserializer deserializer);

  @protected
  List<EngineFrostParticipantPackage>
      sse_decode_list_engine_frost_participant_package(
          SseDeserializer deserializer);

  @protected
  List<EngineFrostPcztActionRequest>
      sse_decode_list_engine_frost_pczt_action_request(
          SseDeserializer deserializer);

  @protected
  List<EngineSharePayload> sse_decode_list_engine_share_payload(
      SseDeserializer deserializer);

  @protected
  List<EngineTransactionRecord> sse_decode_list_engine_transaction_record(
      SseDeserializer deserializer);

  @protected
  List<EngineVanWitness> sse_decode_list_engine_van_witness(
      SseDeserializer deserializer);

  @protected
  List<IronwoodDenomGroup> sse_decode_list_ironwood_denom_group(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<PaymentRecipient> sse_decode_list_payment_recipient(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TransactionRecord> sse_decode_list_transaction_record(
      SseDeserializer deserializer);

  @protected
  List<ValueTransferRecord> sse_decode_list_value_transfer_record(
      SseDeserializer deserializer);

  @protected
  MigrateTarget sse_decode_migrate_target(SseDeserializer deserializer);

  @protected
  MigrationProgress sse_decode_migration_progress(SseDeserializer deserializer);

  @protected
  MigrationRoundResult sse_decode_migration_round_result(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PaymentRecipient sse_decode_payment_recipient(SseDeserializer deserializer);

  @protected
  PolymarketAuthResult sse_decode_polymarket_auth_result(
      SseDeserializer deserializer);

  @protected
  ProposalResult sse_decode_proposal_result(SseDeserializer deserializer);

  @protected
  SyncResultInfo sse_decode_sync_result_info(SseDeserializer deserializer);

  @protected
  SyncStatusInfo sse_decode_sync_status_info(SseDeserializer deserializer);

  @protected
  TransactionRecord sse_decode_transaction_record(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  ValueTransferRecord sse_decode_value_transfer_record(
      SseDeserializer deserializer);

  @protected
  WalletBalance sse_decode_wallet_balance(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_engine_sync_event_Sse(
      RustStreamSink<EngineSyncEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_info(AddressInfo self, SseSerializer serializer);

  @protected
  void sse_encode_address_validation(
      AddressValidation self, SseSerializer serializer);

  @protected
  void sse_encode_auto_migration_status(
      AutoMigrationStatus self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_chain_type(ChainType self, SseSerializer serializer);

  @protected
  void sse_encode_engine_delegation_result(
      EngineDelegationResult self, SseSerializer serializer);

  @protected
  void sse_encode_engine_encrypted_share(
      EngineEncryptedShare self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_action_signature(
      EngineFrostActionSignature self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_aggregate_result(
      EngineFrostAggregateResult self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_dkg_complete_result(
      EngineFrostDkgCompleteResult self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_dkg_round_1_result(
      EngineFrostDkgRound1Result self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_dkg_round_2_result(
      EngineFrostDkgRound2Result self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_participant_package(
      EngineFrostParticipantPackage self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_pczt_action_request(
      EngineFrostPcztActionRequest self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_pczt_signing_request(
      EngineFrostPcztSigningRequest self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_randomizer_result(
      EngineFrostRandomizerResult self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_relay_identity(
      EngineFrostRelayIdentity self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_relay_login_proof(
      EngineFrostRelayLoginProof self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_signing_round_1_result(
      EngineFrostSigningRound1Result self, SseSerializer serializer);

  @protected
  void sse_encode_engine_frost_wallet_view(
      EngineFrostWalletView self, SseSerializer serializer);

  @protected
  void sse_encode_engine_invoice(EngineInvoice self, SseSerializer serializer);

  @protected
  void sse_encode_engine_multi_chain_addresses(
      EngineMultiChainAddresses self, SseSerializer serializer);

  @protected
  void sse_encode_engine_share_payload(
      EngineSharePayload self, SseSerializer serializer);

  @protected
  void sse_encode_engine_sync_event(
      EngineSyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_engine_sync_progress(
      EngineSyncProgress self, SseSerializer serializer);

  @protected
  void sse_encode_engine_transaction_record(
      EngineTransactionRecord self, SseSerializer serializer);

  @protected
  void sse_encode_engine_van_witness(
      EngineVanWitness self, SseSerializer serializer);

  @protected
  void sse_encode_engine_vote_commitment(
      EngineVoteCommitment self, SseSerializer serializer);

  @protected
  void sse_encode_engine_voting_eligibility(
      EngineVotingEligibility self, SseSerializer serializer);

  @protected
  void sse_encode_engine_voting_hotkey(
      EngineVotingHotkey self, SseSerializer serializer);

  @protected
  void sse_encode_evm_fees(EvmFees self, SseSerializer serializer);

  @protected
  void sse_encode_evm_receipt(EvmReceipt self, SseSerializer serializer);

  @protected
  void sse_encode_evm_swap_execute_result(
      EvmSwapExecuteResult self, SseSerializer serializer);

  @protected
  void sse_encode_evm_swap_quote_result(
      EvmSwapQuoteResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ironwood_denom_group(
      IronwoodDenomGroup self, SseSerializer serializer);

  @protected
  void sse_encode_ironwood_plan(IronwoodPlan self, SseSerializer serializer);

  @protected
  void sse_encode_ironwood_reconcile_result(
      IronwoodReconcileResult self, SseSerializer serializer);

  @protected
  void sse_encode_ironwood_sdk_plan(
      IronwoodSdkPlan self, SseSerializer serializer);

  @protected
  void sse_encode_ironwood_sdk_progress(
      IronwoodSdkProgress self, SseSerializer serializer);

  @protected
  void sse_encode_ironwood_tick_result(
      IronwoodTickResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_address_info(
      List<AddressInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_delegation_result(
      List<EngineDelegationResult> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_encrypted_share(
      List<EngineEncryptedShare> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_frost_action_signature(
      List<EngineFrostActionSignature> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_frost_participant_package(
      List<EngineFrostParticipantPackage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_frost_pczt_action_request(
      List<EngineFrostPcztActionRequest> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_share_payload(
      List<EngineSharePayload> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_transaction_record(
      List<EngineTransactionRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_engine_van_witness(
      List<EngineVanWitness> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ironwood_denom_group(
      List<IronwoodDenomGroup> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_payment_recipient(
      List<PaymentRecipient> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
      Uint64List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_transaction_record(
      List<TransactionRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_list_value_transfer_record(
      List<ValueTransferRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_migrate_target(MigrateTarget self, SseSerializer serializer);

  @protected
  void sse_encode_migration_progress(
      MigrationProgress self, SseSerializer serializer);

  @protected
  void sse_encode_migration_round_result(
      MigrationRoundResult self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_payment_recipient(
      PaymentRecipient self, SseSerializer serializer);

  @protected
  void sse_encode_polymarket_auth_result(
      PolymarketAuthResult self, SseSerializer serializer);

  @protected
  void sse_encode_proposal_result(
      ProposalResult self, SseSerializer serializer);

  @protected
  void sse_encode_sync_result_info(
      SyncResultInfo self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status_info(
      SyncStatusInfo self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_record(
      TransactionRecord self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_value_transfer_record(
      ValueTransferRecord self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_balance(WalletBalance self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
