// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiWalletInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1286537798;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_zipher',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiWalletCloseWallet();

  Future<String> crateApiWalletCreateWallet(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType,
      required int chainHeight});

  Future<void> crateApiWalletDeleteWalletData({required String dataDir});

  Future<String?> crateApiWalletExportUfvk();

  Future<List<AddressInfo>> crateApiWalletGetAddresses();

  Future<int> crateApiWalletGetBirthday();

  Future<List<ValueTransferRecord>> crateApiWalletGetMessages({String? filter});

  Future<String?> crateApiWalletGetSeedPhrase();

  Future<String> crateApiWalletGetServerInfo();

  Future<SyncStatusInfo> crateApiWalletGetSyncStatus();

  Future<List<TransactionRecord>> crateApiWalletGetTransactions();

  Future<List<String>> crateApiWalletGetTransparentAddresses();

  Future<List<ValueTransferRecord>> crateApiWalletGetValueTransfers();

  Future<WalletBalance> crateApiWalletGetWalletBalance();

  Future<bool> crateApiWalletHasSpendingKey();

  Future<void> crateApiWalletInitApp();

  Future<void> crateApiWalletOpenWallet(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType});

  Future<void> crateApiWalletPauseSync();

  Future<SyncResultInfo> crateApiWalletRescanWallet();

  Future<void> crateApiWalletRestoreFromSeed(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType,
      required String seedPhrase,
      required int birthday});

  Future<void> crateApiWalletRestoreFromUfvk(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType,
      required String ufvk,
      required int birthday});

  Future<void> crateApiWalletResumeSync();

  Future<String> crateApiWalletSendPayment(
      {required List<PaymentRecipient> recipients});

  Future<void> crateApiWalletSetServer({required String serverUrl});

  Future<String> crateApiWalletShieldFunds();

  Future<void> crateApiWalletStartSaveTask();

  Future<void> crateApiWalletStartSync();

  Future<void> crateApiWalletStopSync();

  Future<SyncResultInfo> crateApiWalletSyncWallet();

  Future<AddressValidation> crateApiWalletValidateAddress(
      {required String address});

  Future<bool> crateApiWalletValidateSeed({required String seed});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiWalletCloseWallet() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletCloseWalletConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletCloseWalletConstMeta => const TaskConstMeta(
        debugName: "close_wallet",
        argNames: [],
      );

  @override
  Future<String> crateApiWalletCreateWallet(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType,
      required int chainHeight}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(serverUrl, serializer);
        sse_encode_chain_type(chainType, serializer);
        sse_encode_u_32(chainHeight, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletCreateWalletConstMeta,
      argValues: [dataDir, serverUrl, chainType, chainHeight],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletCreateWalletConstMeta => const TaskConstMeta(
        debugName: "create_wallet",
        argNames: ["dataDir", "serverUrl", "chainType", "chainHeight"],
      );

  @override
  Future<void> crateApiWalletDeleteWalletData({required String dataDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletDeleteWalletDataConstMeta,
      argValues: [dataDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletDeleteWalletDataConstMeta =>
      const TaskConstMeta(
        debugName: "delete_wallet_data",
        argNames: ["dataDir"],
      );

  @override
  Future<String?> crateApiWalletExportUfvk() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletExportUfvkConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletExportUfvkConstMeta => const TaskConstMeta(
        debugName: "export_ufvk",
        argNames: [],
      );

  @override
  Future<List<AddressInfo>> crateApiWalletGetAddresses() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_address_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetAddressesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetAddressesConstMeta => const TaskConstMeta(
        debugName: "get_addresses",
        argNames: [],
      );

  @override
  Future<int> crateApiWalletGetBirthday() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetBirthdayConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetBirthdayConstMeta => const TaskConstMeta(
        debugName: "get_birthday",
        argNames: [],
      );

  @override
  Future<List<ValueTransferRecord>> crateApiWalletGetMessages(
      {String? filter}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(filter, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_value_transfer_record,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetMessagesConstMeta,
      argValues: [filter],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetMessagesConstMeta => const TaskConstMeta(
        debugName: "get_messages",
        argNames: ["filter"],
      );

  @override
  Future<String?> crateApiWalletGetSeedPhrase() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetSeedPhraseConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetSeedPhraseConstMeta =>
      const TaskConstMeta(
        debugName: "get_seed_phrase",
        argNames: [],
      );

  @override
  Future<String> crateApiWalletGetServerInfo() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetServerInfoConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetServerInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_server_info",
        argNames: [],
      );

  @override
  Future<SyncStatusInfo> crateApiWalletGetSyncStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sync_status_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetSyncStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetSyncStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_sync_status",
        argNames: [],
      );

  @override
  Future<List<TransactionRecord>> crateApiWalletGetTransactions() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_transaction_record,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetTransactionsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetTransactionsConstMeta =>
      const TaskConstMeta(
        debugName: "get_transactions",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiWalletGetTransparentAddresses() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetTransparentAddressesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetTransparentAddressesConstMeta =>
      const TaskConstMeta(
        debugName: "get_transparent_addresses",
        argNames: [],
      );

  @override
  Future<List<ValueTransferRecord>> crateApiWalletGetValueTransfers() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_value_transfer_record,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetValueTransfersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetValueTransfersConstMeta =>
      const TaskConstMeta(
        debugName: "get_value_transfers",
        argNames: [],
      );

  @override
  Future<WalletBalance> crateApiWalletGetWalletBalance() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_wallet_balance,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletGetWalletBalanceConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletGetWalletBalanceConstMeta =>
      const TaskConstMeta(
        debugName: "get_wallet_balance",
        argNames: [],
      );

  @override
  Future<bool> crateApiWalletHasSpendingKey() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletHasSpendingKeyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletHasSpendingKeyConstMeta =>
      const TaskConstMeta(
        debugName: "has_spending_key",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletOpenWallet(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(serverUrl, serializer);
        sse_encode_chain_type(chainType, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletOpenWalletConstMeta,
      argValues: [dataDir, serverUrl, chainType],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletOpenWalletConstMeta => const TaskConstMeta(
        debugName: "open_wallet",
        argNames: ["dataDir", "serverUrl", "chainType"],
      );

  @override
  Future<void> crateApiWalletPauseSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletPauseSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletPauseSyncConstMeta => const TaskConstMeta(
        debugName: "pause_sync",
        argNames: [],
      );

  @override
  Future<SyncResultInfo> crateApiWalletRescanWallet() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sync_result_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletRescanWalletConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletRescanWalletConstMeta => const TaskConstMeta(
        debugName: "rescan_wallet",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletRestoreFromSeed(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType,
      required String seedPhrase,
      required int birthday}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(serverUrl, serializer);
        sse_encode_chain_type(chainType, serializer);
        sse_encode_String(seedPhrase, serializer);
        sse_encode_u_32(birthday, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletRestoreFromSeedConstMeta,
      argValues: [dataDir, serverUrl, chainType, seedPhrase, birthday],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletRestoreFromSeedConstMeta =>
      const TaskConstMeta(
        debugName: "restore_from_seed",
        argNames: [
          "dataDir",
          "serverUrl",
          "chainType",
          "seedPhrase",
          "birthday"
        ],
      );

  @override
  Future<void> crateApiWalletRestoreFromUfvk(
      {required String dataDir,
      required String serverUrl,
      required ChainType chainType,
      required String ufvk,
      required int birthday}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataDir, serializer);
        sse_encode_String(serverUrl, serializer);
        sse_encode_chain_type(chainType, serializer);
        sse_encode_String(ufvk, serializer);
        sse_encode_u_32(birthday, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletRestoreFromUfvkConstMeta,
      argValues: [dataDir, serverUrl, chainType, ufvk, birthday],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletRestoreFromUfvkConstMeta =>
      const TaskConstMeta(
        debugName: "restore_from_ufvk",
        argNames: ["dataDir", "serverUrl", "chainType", "ufvk", "birthday"],
      );

  @override
  Future<void> crateApiWalletResumeSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletResumeSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletResumeSyncConstMeta => const TaskConstMeta(
        debugName: "resume_sync",
        argNames: [],
      );

  @override
  Future<String> crateApiWalletSendPayment(
      {required List<PaymentRecipient> recipients}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_payment_recipient(recipients, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletSendPaymentConstMeta,
      argValues: [recipients],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletSendPaymentConstMeta => const TaskConstMeta(
        debugName: "send_payment",
        argNames: ["recipients"],
      );

  @override
  Future<void> crateApiWalletSetServer({required String serverUrl}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(serverUrl, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletSetServerConstMeta,
      argValues: [serverUrl],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletSetServerConstMeta => const TaskConstMeta(
        debugName: "set_server",
        argNames: ["serverUrl"],
      );

  @override
  Future<String> crateApiWalletShieldFunds() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletShieldFundsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletShieldFundsConstMeta => const TaskConstMeta(
        debugName: "shield_funds",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletStartSaveTask() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletStartSaveTaskConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletStartSaveTaskConstMeta =>
      const TaskConstMeta(
        debugName: "start_save_task",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletStartSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletStartSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletStartSyncConstMeta => const TaskConstMeta(
        debugName: "start_sync",
        argNames: [],
      );

  @override
  Future<void> crateApiWalletStopSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletStopSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletStopSyncConstMeta => const TaskConstMeta(
        debugName: "stop_sync",
        argNames: [],
      );

  @override
  Future<SyncResultInfo> crateApiWalletSyncWallet() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_sync_result_info,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiWalletSyncWalletConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletSyncWalletConstMeta => const TaskConstMeta(
        debugName: "sync_wallet",
        argNames: [],
      );

  @override
  Future<AddressValidation> crateApiWalletValidateAddress(
      {required String address}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(address, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_address_validation,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletValidateAddressConstMeta,
      argValues: [address],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletValidateAddressConstMeta =>
      const TaskConstMeta(
        debugName: "validate_address",
        argNames: ["address"],
      );

  @override
  Future<bool> crateApiWalletValidateSeed({required String seed}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(seed, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiWalletValidateSeedConstMeta,
      argValues: [seed],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWalletValidateSeedConstMeta => const TaskConstMeta(
        debugName: "validate_seed",
        argNames: ["seed"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AddressInfo dco_decode_address_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return AddressInfo(
      address: dco_decode_String(arr[0]),
      hasTransparent: dco_decode_bool(arr[1]),
      hasSapling: dco_decode_bool(arr[2]),
      hasOrchard: dco_decode_bool(arr[3]),
    );
  }

  @protected
  AddressValidation dco_decode_address_validation(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AddressValidation(
      isValid: dco_decode_bool(arr[0]),
      addressType: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ChainType dco_decode_chain_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ChainType.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AddressInfo> dco_decode_list_address_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_address_info).toList();
  }

  @protected
  List<PaymentRecipient> dco_decode_list_payment_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_payment_recipient).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TransactionRecord> dco_decode_list_transaction_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_transaction_record).toList();
  }

  @protected
  List<ValueTransferRecord> dco_decode_list_value_transfer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_value_transfer_record)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  PaymentRecipient dco_decode_payment_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PaymentRecipient(
      address: dco_decode_String(arr[0]),
      amount: dco_decode_u_64(arr[1]),
      memo: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  SyncResultInfo dco_decode_sync_result_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SyncResultInfo(
      startHeight: dco_decode_u_32(arr[0]),
      endHeight: dco_decode_u_32(arr[1]),
      blocksScanned: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  SyncStatusInfo dco_decode_sync_status_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return SyncStatusInfo(
      mode: dco_decode_String(arr[0]),
    );
  }

  @protected
  TransactionRecord dco_decode_transaction_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TransactionRecord(
      txid: dco_decode_String(arr[0]),
      height: dco_decode_u_32(arr[1]),
      timestamp: dco_decode_u_64(arr[2]),
      value: dco_decode_i_64(arr[3]),
      kind: dco_decode_String(arr[4]),
      fee: dco_decode_opt_box_autoadd_u_64(arr[5]),
      status: dco_decode_String(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  ValueTransferRecord dco_decode_value_transfer_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return ValueTransferRecord(
      txid: dco_decode_String(arr[0]),
      height: dco_decode_u_32(arr[1]),
      timestamp: dco_decode_u_64(arr[2]),
      value: dco_decode_u_64(arr[3]),
      kind: dco_decode_String(arr[4]),
      fee: dco_decode_opt_box_autoadd_u_64(arr[5]),
      recipientAddress: dco_decode_opt_String(arr[6]),
      poolReceived: dco_decode_opt_String(arr[7]),
      memos: dco_decode_list_String(arr[8]),
      status: dco_decode_String(arr[9]),
    );
  }

  @protected
  WalletBalance dco_decode_wallet_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return WalletBalance(
      transparent: dco_decode_u_64(arr[0]),
      sapling: dco_decode_u_64(arr[1]),
      orchard: dco_decode_u_64(arr[2]),
      unconfirmedSapling: dco_decode_u_64(arr[3]),
      unconfirmedOrchard: dco_decode_u_64(arr[4]),
      unconfirmedTransparent: dco_decode_u_64(arr[5]),
      totalTransparent: dco_decode_u_64(arr[6]),
      totalSapling: dco_decode_u_64(arr[7]),
      totalOrchard: dco_decode_u_64(arr[8]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AddressInfo sse_decode_address_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_hasTransparent = sse_decode_bool(deserializer);
    var var_hasSapling = sse_decode_bool(deserializer);
    var var_hasOrchard = sse_decode_bool(deserializer);
    return AddressInfo(
        address: var_address,
        hasTransparent: var_hasTransparent,
        hasSapling: var_hasSapling,
        hasOrchard: var_hasOrchard);
  }

  @protected
  AddressValidation sse_decode_address_validation(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isValid = sse_decode_bool(deserializer);
    var var_addressType = sse_decode_opt_String(deserializer);
    return AddressValidation(
        isValid: var_isValid, addressType: var_addressType);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ChainType sse_decode_chain_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ChainType.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AddressInfo> sse_decode_list_address_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AddressInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_address_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<PaymentRecipient> sse_decode_list_payment_recipient(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PaymentRecipient>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_payment_recipient(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TransactionRecord> sse_decode_list_transaction_record(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TransactionRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_transaction_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<ValueTransferRecord> sse_decode_list_value_transfer_record(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ValueTransferRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_value_transfer_record(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PaymentRecipient sse_decode_payment_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_amount = sse_decode_u_64(deserializer);
    var var_memo = sse_decode_opt_String(deserializer);
    return PaymentRecipient(
        address: var_address, amount: var_amount, memo: var_memo);
  }

  @protected
  SyncResultInfo sse_decode_sync_result_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startHeight = sse_decode_u_32(deserializer);
    var var_endHeight = sse_decode_u_32(deserializer);
    var var_blocksScanned = sse_decode_u_32(deserializer);
    return SyncResultInfo(
        startHeight: var_startHeight,
        endHeight: var_endHeight,
        blocksScanned: var_blocksScanned);
  }

  @protected
  SyncStatusInfo sse_decode_sync_status_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mode = sse_decode_String(deserializer);
    return SyncStatusInfo(mode: var_mode);
  }

  @protected
  TransactionRecord sse_decode_transaction_record(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_String(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_value = sse_decode_i_64(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_fee = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return TransactionRecord(
        txid: var_txid,
        height: var_height,
        timestamp: var_timestamp,
        value: var_value,
        kind: var_kind,
        fee: var_fee,
        status: var_status);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  ValueTransferRecord sse_decode_value_transfer_record(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_String(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_value = sse_decode_u_64(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_fee = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_recipientAddress = sse_decode_opt_String(deserializer);
    var var_poolReceived = sse_decode_opt_String(deserializer);
    var var_memos = sse_decode_list_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return ValueTransferRecord(
        txid: var_txid,
        height: var_height,
        timestamp: var_timestamp,
        value: var_value,
        kind: var_kind,
        fee: var_fee,
        recipientAddress: var_recipientAddress,
        poolReceived: var_poolReceived,
        memos: var_memos,
        status: var_status);
  }

  @protected
  WalletBalance sse_decode_wallet_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_transparent = sse_decode_u_64(deserializer);
    var var_sapling = sse_decode_u_64(deserializer);
    var var_orchard = sse_decode_u_64(deserializer);
    var var_unconfirmedSapling = sse_decode_u_64(deserializer);
    var var_unconfirmedOrchard = sse_decode_u_64(deserializer);
    var var_unconfirmedTransparent = sse_decode_u_64(deserializer);
    var var_totalTransparent = sse_decode_u_64(deserializer);
    var var_totalSapling = sse_decode_u_64(deserializer);
    var var_totalOrchard = sse_decode_u_64(deserializer);
    return WalletBalance(
        transparent: var_transparent,
        sapling: var_sapling,
        orchard: var_orchard,
        unconfirmedSapling: var_unconfirmedSapling,
        unconfirmedOrchard: var_unconfirmedOrchard,
        unconfirmedTransparent: var_unconfirmedTransparent,
        totalTransparent: var_totalTransparent,
        totalSapling: var_totalSapling,
        totalOrchard: var_totalOrchard);
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_address_info(AddressInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_bool(self.hasTransparent, serializer);
    sse_encode_bool(self.hasSapling, serializer);
    sse_encode_bool(self.hasOrchard, serializer);
  }

  @protected
  void sse_encode_address_validation(
      AddressValidation self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isValid, serializer);
    sse_encode_opt_String(self.addressType, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_chain_type(ChainType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_address_info(
      List<AddressInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_address_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_payment_recipient(
      List<PaymentRecipient> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_payment_recipient(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_transaction_record(
      List<TransactionRecord> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_transaction_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_value_transfer_record(
      List<ValueTransferRecord> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_value_transfer_record(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_payment_recipient(
      PaymentRecipient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_u_64(self.amount, serializer);
    sse_encode_opt_String(self.memo, serializer);
  }

  @protected
  void sse_encode_sync_result_info(
      SyncResultInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.startHeight, serializer);
    sse_encode_u_32(self.endHeight, serializer);
    sse_encode_u_32(self.blocksScanned, serializer);
  }

  @protected
  void sse_encode_sync_status_info(
      SyncStatusInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mode, serializer);
  }

  @protected
  void sse_encode_transaction_record(
      TransactionRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txid, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_i_64(self.value, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_box_autoadd_u_64(self.fee, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_value_transfer_record(
      ValueTransferRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txid, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_u_64(self.value, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_box_autoadd_u_64(self.fee, serializer);
    sse_encode_opt_String(self.recipientAddress, serializer);
    sse_encode_opt_String(self.poolReceived, serializer);
    sse_encode_list_String(self.memos, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_wallet_balance(WalletBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.transparent, serializer);
    sse_encode_u_64(self.sapling, serializer);
    sse_encode_u_64(self.orchard, serializer);
    sse_encode_u_64(self.unconfirmedSapling, serializer);
    sse_encode_u_64(self.unconfirmedOrchard, serializer);
    sse_encode_u_64(self.unconfirmedTransparent, serializer);
    sse_encode_u_64(self.totalTransparent, serializer);
    sse_encode_u_64(self.totalSapling, serializer);
    sse_encode_u_64(self.totalOrchard, serializer);
  }
}
