// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wallet.dart';

// These functions are ignored because they are not marked as `pub`: `to_network`

/// Create a new wallet. Returns the 24-word seed phrase.
Future<String> engineCreateWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required int chainHeight,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineCreateWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        chainHeight: chainHeight,
        dbCipherKey: dbCipherKey);

/// Restore a wallet from a BIP39 seed phrase.
Future<void> engineRestoreFromSeed(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String seedPhrase,
        required int birthday,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineRestoreFromSeed(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        seedPhrase: seedPhrase,
        birthday: birthday,
        dbCipherKey: dbCipherKey);

/// Restore a watch-only wallet from a UFVK.
Future<void> engineRestoreFromUfvk(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String ufvk,
        required int birthday,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineRestoreFromUfvk(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        ufvk: ufvk,
        birthday: birthday,
        dbCipherKey: dbCipherKey);

/// Open an existing wallet from disk.
Future<void> engineOpenWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineOpenWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        dbCipherKey: dbCipherKey);

/// Close the current wallet.
Future<void> engineCloseWallet() =>
    RustLib.instance.api.crateApiEngineApiEngineCloseWallet();

/// Delete wallet database files from disk.
Future<void> engineDeleteWalletData({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineDeleteWalletData(dataDir: dataDir);

Future<List<AddressInfo>> engineGetAddresses() =>
    RustLib.instance.api.crateApiEngineApiEngineGetAddresses();

Future<List<String>> engineGetTransparentAddresses() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransparentAddresses();

Future<WalletBalance> engineGetWalletBalance() =>
    RustLib.instance.api.crateApiEngineApiEngineGetWalletBalance();

/// Returns the maximum amount (in zatoshis) that can be sent to the given
/// address after accounting for the exact ZIP-317 fee.
Future<BigInt> engineGetMaxSendable({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetMaxSendable(address: address);

Future<int> engineGetBirthday() =>
    RustLib.instance.api.crateApiEngineApiEngineGetBirthday();

Future<int> engineGetWalletSyncedHeight() =>
    RustLib.instance.api.crateApiEngineApiEngineGetWalletSyncedHeight();

Future<bool> engineHasSpendingKey() =>
    RustLib.instance.api.crateApiEngineApiEngineHasSpendingKey();

Future<String?> engineExportUfvk() =>
    RustLib.instance.api.crateApiEngineApiEngineExportUfvk();

Future<AddressValidation> engineValidateAddress({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineValidateAddress(address: address);

Future<bool> engineValidateSeed({required String seed}) =>
    RustLib.instance.api.crateApiEngineApiEngineValidateSeed(seed: seed);

Future<int> engineGetLatestBlockHeight({required String serverUrl}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetLatestBlockHeight(serverUrl: serverUrl);

Future<void> engineStartSync() =>
    RustLib.instance.api.crateApiEngineApiEngineStartSync();

Future<void> engineStopSync() =>
    RustLib.instance.api.crateApiEngineApiEngineStopSync();

Future<EngineSyncProgress> engineGetSyncProgress() =>
    RustLib.instance.api.crateApiEngineApiEngineGetSyncProgress();

Future<void> engineRegisterInactiveWallet({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineRegisterInactiveWallet(dataDir: dataDir);

Future<void> engineUnregisterInactiveWallet({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineUnregisterInactiveWallet(dataDir: dataDir);

Future<void> engineClearInactiveWallets() =>
    RustLib.instance.api.crateApiEngineApiEngineClearInactiveWallets();

/// Step 1: Create a proposal and return exact fee info.
/// When `is_max` is true, `amount` is ignored and the SDK computes the max sendable.
Future<ProposalResult> engineProposeSend(
        {required String address,
        required BigInt amount,
        String? memo,
        required bool isMax}) =>
    RustLib.instance.api.crateApiEngineApiEngineProposeSend(
        address: address, amount: amount, memo: memo, isMax: isMax);

/// Step 2: Confirm and broadcast the previously proposed transaction.
Future<String> engineConfirmSend({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineConfirmSend(seedPhrase: seedPhrase);

/// Legacy single-step send (still used for multi-recipient or fallback).
Future<String> engineSendPayment(
        {required String seedPhrase,
        required String address,
        required BigInt amount,
        String? memo}) =>
    RustLib.instance.api.crateApiEngineApiEngineSendPayment(
        seedPhrase: seedPhrase, address: address, amount: amount, memo: memo);

/// Shield transparent funds into the shielded pool.
Future<String> engineShieldFunds({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineShieldFunds(seedPhrase: seedPhrase);

Future<List<EngineTransactionRecord>> engineGetTransactions() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransactions();

/// Sync progress reported to Dart.
class EngineSyncProgress {
  final int syncedHeight;
  final int latestHeight;
  final bool isSyncing;
  final String? connectionError;
  final int scanningUpTo;

  const EngineSyncProgress({
    required this.syncedHeight,
    required this.latestHeight,
    required this.isSyncing,
    this.connectionError,
    required this.scanningUpTo,
  });

  @override
  int get hashCode =>
      syncedHeight.hashCode ^
      latestHeight.hashCode ^
      isSyncing.hashCode ^
      connectionError.hashCode ^
      scanningUpTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineSyncProgress &&
          runtimeType == other.runtimeType &&
          syncedHeight == other.syncedHeight &&
          latestHeight == other.latestHeight &&
          isSyncing == other.isSyncing &&
          connectionError == other.connectionError &&
          scanningUpTo == other.scanningUpTo;
}

class EngineTransactionRecord {
  final String txid;
  final int height;
  final int timestamp;
  final PlatformInt64 value;
  final String kind;
  final BigInt? fee;
  final String? memo;
  final bool expiredUnmined;

  const EngineTransactionRecord({
    required this.txid,
    required this.height,
    required this.timestamp,
    required this.value,
    required this.kind,
    this.fee,
    this.memo,
    required this.expiredUnmined,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      timestamp.hashCode ^
      value.hashCode ^
      kind.hashCode ^
      fee.hashCode ^
      memo.hashCode ^
      expiredUnmined.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineTransactionRecord &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          timestamp == other.timestamp &&
          value == other.value &&
          kind == other.kind &&
          fee == other.fee &&
          memo == other.memo &&
          expiredUnmined == other.expiredUnmined;
}

/// Proposal result returned to Dart.
class ProposalResult {
  final BigInt sendAmount;
  final BigInt fee;
  final bool isExact;

  const ProposalResult({
    required this.sendAmount,
    required this.fee,
    required this.isExact,
  });

  @override
  int get hashCode => sendAmount.hashCode ^ fee.hashCode ^ isExact.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalResult &&
          runtimeType == other.runtimeType &&
          sendAmount == other.sendAmount &&
          fee == other.fee &&
          isExact == other.isExact;
}
