// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wallet.dart';

// These functions are ignored because they are not marked as `pub`: `packages_from_map`, `packages_to_map`, `to_network`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Create a new wallet. Returns the 24-word seed phrase.
Future<String> engineCreateWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required int chainHeight,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineCreateWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        chainHeight: chainHeight,
        dbCipherKey: dbCipherKey);

/// Restore a wallet from a BIP39 seed phrase.
Future<void> engineRestoreFromSeed(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String seedPhrase,
        required int birthday,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineRestoreFromSeed(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        seedPhrase: seedPhrase,
        birthday: birthday,
        dbCipherKey: dbCipherKey);

/// Restore a watch-only wallet from a UFVK.
Future<void> engineRestoreFromUfvk(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String ufvk,
        required int birthday,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineRestoreFromUfvk(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        ufvk: ufvk,
        birthday: birthday,
        dbCipherKey: dbCipherKey);

/// Open an existing wallet from disk.
Future<void> engineOpenWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineOpenWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        dbCipherKey: dbCipherKey);

/// Close the current wallet.
Future<void> engineCloseWallet() =>
    RustLib.instance.api.crateApiEngineApiEngineCloseWallet();

/// Delete wallet database files from disk.
Future<void> engineDeleteWalletData({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineDeleteWalletData(dataDir: dataDir);

Future<List<AddressInfo>> engineGetAddresses() =>
    RustLib.instance.api.crateApiEngineApiEngineGetAddresses();

Future<List<String>> engineGetTransparentAddresses() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransparentAddresses();

Future<WalletBalance> engineGetWalletBalance() =>
    RustLib.instance.api.crateApiEngineApiEngineGetWalletBalance();

/// Returns the maximum amount (in zatoshis) that can be sent to the given
/// address after accounting for the exact ZIP-317 fee.
Future<BigInt> engineGetMaxSendable({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetMaxSendable(address: address);

Future<int> engineGetBirthday() =>
    RustLib.instance.api.crateApiEngineApiEngineGetBirthday();

Future<int> engineGetWalletSyncedHeight() =>
    RustLib.instance.api.crateApiEngineApiEngineGetWalletSyncedHeight();

/// Native balance in raw wei as decimal string.
Future<String> engineGetNativeBalance(
        {required String rpcUrl, required String address}) =>
    RustLib.instance.api.crateApiEngineApiEngineGetNativeBalance(
        rpcUrl: rpcUrl, address: address);

/// ERC-20 balance in raw token units as decimal string.
Future<String> engineGetErc20Balance(
        {required String rpcUrl,
        required String tokenContract,
        required String ownerAddress}) =>
    RustLib.instance.api.crateApiEngineApiEngineGetErc20Balance(
        rpcUrl: rpcUrl,
        tokenContract: tokenContract,
        ownerAddress: ownerAddress);

/// Pending nonce for an address.
Future<BigInt> engineGetNonce(
        {required String rpcUrl, required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetNonce(rpcUrl: rpcUrl, address: address);

/// Suggested EIP-1559 gas fees. Returns (maxPriorityFeePerGas, maxFeePerGas) in wei.
Future<EvmFees> engineSuggestEip1559Fees(
        {required String rpcUrl, required BigInt chainId}) =>
    RustLib.instance.api.crateApiEngineApiEngineSuggestEip1559Fees(
        rpcUrl: rpcUrl, chainId: chainId);

/// ERC-20 approve: sign + broadcast + wait. Returns tx hash.
Future<String> engineApproveErc20(
        {required String rpcUrl,
        required String seedPhrase,
        required String ownerAddress,
        required String tokenAddress,
        required String spenderAddress,
        required String amountRaw,
        required BigInt chainId}) =>
    RustLib.instance.api.crateApiEngineApiEngineApproveErc20(
        rpcUrl: rpcUrl,
        seedPhrase: seedPhrase,
        ownerAddress: ownerAddress,
        tokenAddress: tokenAddress,
        spenderAddress: spenderAddress,
        amountRaw: amountRaw,
        chainId: chainId);

/// Wait for a tx receipt. Returns (success, block_number).
Future<EvmReceipt> engineWaitForReceipt(
        {required String rpcUrl, required String txHash}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineWaitForReceipt(rpcUrl: rpcUrl, txHash: txHash);

/// ERC-1155 isApprovedForAll check.
Future<bool> engineErc1155IsApprovedForAll(
        {required String rpcUrl,
        required String owner,
        required String tokenContract,
        required String operator_}) =>
    RustLib.instance.api.crateApiEngineApiEngineErc1155IsApprovedForAll(
        rpcUrl: rpcUrl,
        owner: owner,
        tokenContract: tokenContract,
        operator_: operator_);

/// ERC-1155 setApprovalForAll: sign + broadcast + wait. Returns tx hash.
Future<String> engineErc1155SetApprovalForAll(
        {required String rpcUrl,
        required String seedPhrase,
        required String ownerAddress,
        required String tokenContract,
        required String operator_,
        required bool approved,
        required BigInt chainId}) =>
    RustLib.instance.api.crateApiEngineApiEngineErc1155SetApprovalForAll(
        rpcUrl: rpcUrl,
        seedPhrase: seedPhrase,
        ownerAddress: ownerAddress,
        tokenContract: tokenContract,
        operator_: operator_,
        approved: approved,
        chainId: chainId);

Future<bool> engineHasSpendingKey() =>
    RustLib.instance.api.crateApiEngineApiEngineHasSpendingKey();

Future<String?> engineExportUfvk() =>
    RustLib.instance.api.crateApiEngineApiEngineExportUfvk();

Future<AddressValidation> engineValidateAddress({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineValidateAddress(address: address);

Future<bool> engineValidateSeed({required String seed}) =>
    RustLib.instance.api.crateApiEngineApiEngineValidateSeed(seed: seed);

Future<int> engineGetLatestBlockHeight({required String serverUrl}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetLatestBlockHeight(serverUrl: serverUrl);

Future<void> engineStartSync() =>
    RustLib.instance.api.crateApiEngineApiEngineStartSync();

Future<void> engineStopSync() =>
    RustLib.instance.api.crateApiEngineApiEngineStopSync();

Future<void> engineSetServer({required String serverUrl}) =>
    RustLib.instance.api.crateApiEngineApiEngineSetServer(serverUrl: serverUrl);

/// Rescan the wallet from its birthday height by truncating and restarting sync.
Future<void> engineRescanFromBirthday() =>
    RustLib.instance.api.crateApiEngineApiEngineRescanFromBirthday();

Future<EngineSyncProgress> engineGetSyncProgress() =>
    RustLib.instance.api.crateApiEngineApiEngineGetSyncProgress();

Stream<EngineSyncEvent> engineSyncEvents() =>
    RustLib.instance.api.crateApiEngineApiEngineSyncEvents();

Future<void> engineEnhanceTransaction({required String txid}) =>
    RustLib.instance.api.crateApiEngineApiEngineEnhanceTransaction(txid: txid);

Future<void> engineRegisterInactiveWallet({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineRegisterInactiveWallet(dataDir: dataDir);

Future<void> engineUnregisterInactiveWallet({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineUnregisterInactiveWallet(dataDir: dataDir);

Future<void> engineClearInactiveWallets() =>
    RustLib.instance.api.crateApiEngineApiEngineClearInactiveWallets();

/// Step 1: Create a proposal and return exact fee info.
/// When `is_max` is true, `amount` is ignored and the SDK computes the max sendable.
/// When `priority` is true, a 4x marginal fee is applied for faster confirmation.
Future<ProposalResult> engineProposeSend(
        {required String address,
        required BigInt amount,
        String? memo,
        required bool isMax,
        required bool priority}) =>
    RustLib.instance.api.crateApiEngineApiEngineProposeSend(
        address: address,
        amount: amount,
        memo: memo,
        isMax: isMax,
        priority: priority);

/// Create a proved PCZT from the pending proposal.
///
/// This consumes the same pending proposal created by [`engine_propose_send`],
/// but stops before signing so a hardware signer or FROST ceremony can add
/// spend authorization signatures.
Future<Uint8List> engineCreatePczt() =>
    RustLib.instance.api.crateApiEngineApiEngineCreatePczt();

/// Create a proved PCZT for transparent -> shielded funds.
Future<Uint8List> engineCreateShieldPczt() =>
    RustLib.instance.api.crateApiEngineApiEngineCreateShieldPczt();

/// Store a fully signed PCZT back into the wallet DB and return the txid.
Future<String> engineStoreSignedPczt({required List<int> signedPcztBytes}) =>
    RustLib.instance.api.crateApiEngineApiEngineStoreSignedPczt(
        signedPcztBytes: signedPcztBytes);

Future<EngineFrostDkgRound1Result> engineFrostDkgInit(
        {required int participantId,
        required int maxSigners,
        required int minSigners}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostDkgInit(
        participantId: participantId,
        maxSigners: maxSigners,
        minSigners: minSigners);

Future<EngineFrostDkgRound2Result> engineFrostDkgRound2(
        {required String secretPackage,
        required List<EngineFrostParticipantPackage> round1Packages}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostDkgRound2(
        secretPackage: secretPackage, round1Packages: round1Packages);

Future<EngineFrostDkgCompleteResult> engineFrostDkgRound3(
        {required String secretPackage,
        required List<EngineFrostParticipantPackage> round1Packages,
        required List<EngineFrostParticipantPackage> round2Packages}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostDkgRound3(
        secretPackage: secretPackage,
        round1Packages: round1Packages,
        round2Packages: round2Packages);

Future<EngineFrostSigningRound1Result> engineFrostSignRound1(
        {required String keyPackage}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineFrostSignRound1(keyPackage: keyPackage);

Future<String> engineFrostCreateSigningPackage(
        {required String messageHex,
        required List<EngineFrostParticipantPackage> commitments}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostCreateSigningPackage(
        messageHex: messageHex, commitments: commitments);

Future<EngineFrostRandomizerResult> engineFrostCreateRandomizer(
        {required String publicKeyPackage}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostCreateRandomizer(
        publicKeyPackage: publicKeyPackage);

Future<String> engineFrostSignRound2(
        {required String signingPackage,
        required String signingNonces,
        required String keyPackage,
        required String randomizerPointHex}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostSignRound2(
        signingPackage: signingPackage,
        signingNonces: signingNonces,
        keyPackage: keyPackage,
        randomizerPointHex: randomizerPointHex);

Future<EngineFrostAggregateResult> engineFrostAggregate(
        {required String signingPackage,
        required List<EngineFrostParticipantPackage> signatureShares,
        required String publicKeyPackage,
        required String randomizerHex}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostAggregate(
        signingPackage: signingPackage,
        signatureShares: signatureShares,
        publicKeyPackage: publicKeyPackage,
        randomizerHex: randomizerHex);

Future<EngineFrostPcztSigningRequest> engineFrostPcztSigningRequest(
        {required List<int> pcztBytes}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineFrostPcztSigningRequest(pcztBytes: pcztBytes);

Future<Uint8List> engineFrostPcztApplySignatures(
        {required List<int> pcztBytes,
        required List<EngineFrostActionSignature> orchardSignatures}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostPcztApplySignatures(
        pcztBytes: pcztBytes, orchardSignatures: orchardSignatures);

Future<String> engineFrostDeriveUfvk({required String groupPublicKeyHex}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostDeriveUfvk(
        groupPublicKeyHex: groupPublicKeyHex);

Future<String> engineFrostKeyRefresh(
        {required String keyPackage, required int newSignerCount}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostKeyRefresh(
        keyPackage: keyPackage, newSignerCount: newSignerCount);

Future<EngineFrostWalletView> engineFrostCreateViewFromGroupKey(
        {required String groupPublicKeyHex, required ChainType chainType}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostCreateViewFromGroupKey(
        groupPublicKeyHex: groupPublicKeyHex, chainType: chainType);

Future<EngineFrostRelayIdentity> engineFrostRelayGenerateIdentity() =>
    RustLib.instance.api.crateApiEngineApiEngineFrostRelayGenerateIdentity();

Future<EngineFrostRelayLoginProof> engineFrostRelaySignChallenge(
        {required String privateKeyHex,
        required String publicKeyHex,
        required String challenge}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostRelaySignChallenge(
        privateKeyHex: privateKeyHex,
        publicKeyHex: publicKeyHex,
        challenge: challenge);

Future<String> engineFrostRelayEncrypt(
        {required String senderPrivateKeyHex,
        required String recipientPublicKeyHex,
        required String messageHex}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostRelayEncrypt(
        senderPrivateKeyHex: senderPrivateKeyHex,
        recipientPublicKeyHex: recipientPublicKeyHex,
        messageHex: messageHex);

Future<String> engineFrostRelayDecrypt(
        {required String recipientPrivateKeyHex,
        required String senderPublicKeyHex,
        required String encryptedHex}) =>
    RustLib.instance.api.crateApiEngineApiEngineFrostRelayDecrypt(
        recipientPrivateKeyHex: recipientPrivateKeyHex,
        senderPublicKeyHex: senderPublicKeyHex,
        encryptedHex: encryptedHex);

/// Step 2: Confirm and broadcast the previously proposed transaction.
Future<String> engineConfirmSend({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineConfirmSend(seedPhrase: seedPhrase);

/// Legacy single-step send (still used for multi-recipient or fallback).
Future<String> engineSendPayment(
        {required String seedPhrase,
        required String address,
        required BigInt amount,
        String? memo}) =>
    RustLib.instance.api.crateApiEngineApiEngineSendPayment(
        seedPhrase: seedPhrase, address: address, amount: amount, memo: memo);

/// Shield transparent funds into the shielded pool.
Future<String> engineShieldFunds({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineShieldFunds(seedPhrase: seedPhrase);

Future<List<EngineTransactionRecord>> engineGetTransactions() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransactions();

/// Derive the EVM (BSC/ETH) address from the wallet's BIP-39 seed phrase.
/// Uses the standard BIP-44 path m/44'/60'/0'/0/0.
Future<String> engineDeriveEvmAddress({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineDeriveEvmAddress(seedPhrase: seedPhrase);

/// Derive addresses for EVM, Solana, and Bitcoin from a single seed phrase.
/// All derivation is CPU-only (no network calls).
Future<EngineMultiChainAddresses> engineDeriveMultiChainAddresses(
        {required String seedPhrase}) =>
    RustLib.instance.api.crateApiEngineApiEngineDeriveMultiChainAddresses(
        seedPhrase: seedPhrase);

/// Sign an unsigned EVM transaction and return the broadcast-ready signed bytes.
Future<String> engineSignEvmTx(
        {required String seedPhrase, required String unsignedTxHex}) =>
    RustLib.instance.api.crateApiEngineApiEngineSignEvmTx(
        seedPhrase: seedPhrase, unsignedTxHex: unsignedTxHex);

/// Sign an unsigned EVM transaction, broadcast it via JSON-RPC, and return the tx hash.
Future<String> engineSignAndBroadcastEvmTx(
        {required String seedPhrase,
        required String unsignedTxHex,
        required String rpcUrl}) =>
    RustLib.instance.api.crateApiEngineApiEngineSignAndBroadcastEvmTx(
        seedPhrase: seedPhrase, unsignedTxHex: unsignedTxHex, rpcUrl: rpcUrl);

/// Load a GGUF model and tokenizer from the given file paths.
/// Must be called before `engine_llm_infer`. Blocks while loading (~1-5s).
Future<void> engineLlmLoad(
        {required String modelPath, required String tokenizerPath}) =>
    RustLib.instance.api.crateApiEngineApiEngineLlmLoad(
        modelPath: modelPath, tokenizerPath: tokenizerPath);

/// Unload the LLM from memory.
Future<void> engineLlmUnload() =>
    RustLib.instance.api.crateApiEngineApiEngineLlmUnload();

/// Check if an LLM model is currently loaded.
Future<bool> engineLlmIsLoaded() =>
    RustLib.instance.api.crateApiEngineApiEngineLlmIsLoaded();

/// Run LLM inference on a raw prompt. Returns the generated text.
Future<String> engineLlmInfer(
        {required String prompt,
        required int maxTokens,
        required double temperature}) =>
    RustLib.instance.api.crateApiEngineApiEngineLlmInfer(
        prompt: prompt, maxTokens: maxTokens, temperature: temperature);

/// Build an intent-classification prompt from the user's natural language input.
/// The returned prompt is ready to pass to `engine_llm_infer`.
Future<String> engineLlmBuildIntentPrompt({required String userInput}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineLlmBuildIntentPrompt(userInput: userInput);

/// Get the recommended model filename, display name, and expected size in bytes.
Future<EngineLlmModelInfo> engineLlmRecommendedModel() =>
    RustLib.instance.api.crateApiEngineApiEngineLlmRecommendedModel();

/// Sign the CLOB L1 auth message to derive API credentials.
/// Returns (polygon_address, eip712_signature_hex).
Future<PolymarketAuthResult> enginePolymarketSignAuth(
        {required String seedPhrase,
        required BigInt timestamp,
        required BigInt nonce}) =>
    RustLib.instance.api.crateApiEngineApiEnginePolymarketSignAuth(
        seedPhrase: seedPhrase, timestamp: timestamp, nonce: nonce);

/// Sign a Polymarket CLOB V2 order with EIP-712.
/// Returns the hex-encoded signature.
Future<String> enginePolymarketSignOrder(
        {required String seedPhrase,
        required String salt,
        required String maker,
        required String signer,
        required String tokenId,
        required String makerAmount,
        required String takerAmount,
        required int side,
        required int signatureType,
        required String timestamp,
        required String metadata,
        required String builder,
        required bool negRisk}) =>
    RustLib.instance.api.crateApiEngineApiEnginePolymarketSignOrder(
        seedPhrase: seedPhrase,
        salt: salt,
        maker: maker,
        signer: signer,
        tokenId: tokenId,
        makerAmount: makerAmount,
        takerAmount: takerAmount,
        side: side,
        signatureType: signatureType,
        timestamp: timestamp,
        metadata: metadata,
        builder: builder,
        negRisk: negRisk);

/// Whether one Gamma `/markets` or nested event market object passes the default
/// tradability filter (same rules as `zipher-cli polymarket list`). Pure JSON — no wallet.
Future<bool> enginePolymarketGammaMarketPassesQualityFilter(
        {required String marketJson, required bool relaxed}) =>
    RustLib.instance.api
        .crateApiEngineApiEnginePolymarketGammaMarketPassesQualityFilter(
            marketJson: marketJson, relaxed: relaxed);

/// Polymarket discovery: Gamma events + Rust grouping/quality (same as CLI `polymarket list`).
/// Returns JSON `PolymarketDiscoverySummary`.
Future<String> enginePolymarketDiscover(
        {String? keyword, required int limit}) =>
    RustLib.instance.api.crateApiEngineApiEnginePolymarketDiscover(
        keyword: keyword, limit: limit);

/// Polymarket open positions for `user` (0x + 40 hex) via public Data API.
/// Returns JSON array of `PolymarketPosition`.
Future<String> enginePolymarketGetPositions({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEnginePolymarketGetPositions(address: address);

/// Get a ParaSwap quote for a same-chain EVM swap.
Future<EvmSwapQuoteResult> engineEvmSwapQuote(
        {required BigInt chainId,
        required String srcToken,
        required int srcDecimals,
        required String destToken,
        required int destDecimals,
        required String amountRaw,
        required String userAddress}) =>
    RustLib.instance.api.crateApiEngineApiEngineEvmSwapQuote(
        chainId: chainId,
        srcToken: srcToken,
        srcDecimals: srcDecimals,
        destToken: destToken,
        destDecimals: destDecimals,
        amountRaw: amountRaw,
        userAddress: userAddress);

/// Execute a full same-chain EVM swap: quote -> approve (if ERC-20) -> build -> sign -> broadcast -> wait.
/// All RLP encoding, signing, and broadcasting happens in Rust.
Future<EvmSwapExecuteResult> engineEvmSwapExecute(
        {required String rpcUrl,
        required String seedPhrase,
        required BigInt chainId,
        required String userAddress,
        required String srcToken,
        required int srcDecimals,
        required String destToken,
        required int destDecimals,
        required String amountRaw,
        required int slippageBps}) =>
    RustLib.instance.api.crateApiEngineApiEngineEvmSwapExecute(
        rpcUrl: rpcUrl,
        seedPhrase: seedPhrase,
        chainId: chainId,
        userAddress: userAddress,
        srcToken: srcToken,
        srcDecimals: srcDecimals,
        destToken: destToken,
        destDecimals: destDecimals,
        amountRaw: amountRaw,
        slippageBps: slippageBps);

/// Fetch a CipherPay invoice by UUID or memo code (e.g. `CP-A7F3B2C1`).
///
/// SAFETY/PRIVACY: the customer's IP is exposed to `api.cipherpay.app` for the
/// duration of this call. Callers should only invoke this in response to an
/// explicit user action (scanning a QR, tapping a checkout link, manually
/// pasting an invoice id). Never poll silently in the background.
Future<EngineInvoice> engineCheckInvoice({required String idOrMemo}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineCheckInvoice(idOrMemo: idOrMemo);

/// Warm the proving key caches for voting ZKPs. Takes ~30s.
/// Call once from a background isolate at app startup.
Future<void> engineVoteWarmCaches() =>
    RustLib.instance.api.crateApiEngineApiEngineVoteWarmCaches();

/// Derive the voting seed from raw BIP-39 seed bytes (deterministic).
Future<Uint8List> engineVoteDeriveSeed({required List<int> walletSeed}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineVoteDeriveSeed(walletSeed: walletSeed);

/// Derive the voting seed from a BIP-39 mnemonic phrase.
Future<Uint8List> engineVoteDeriveSeedFromPhrase(
        {required String seedPhrase}) =>
    RustLib.instance.api.crateApiEngineApiEngineVoteDeriveSeedFromPhrase(
        seedPhrase: seedPhrase);

/// Derive a voting hotkey from a 32-byte voting seed.
Future<EngineVotingHotkey> engineVoteDeriveHotkey(
        {required List<int> votingSeed}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineVoteDeriveHotkey(votingSeed: votingSeed);

/// Check voting eligibility at a given snapshot height.
Future<EngineVotingEligibility> engineVoteCheckEligibility(
        {required BigInt snapshotHeight}) =>
    RustLib.instance.api.crateApiEngineApiEngineVoteCheckEligibility(
        snapshotHeight: snapshotHeight);

/// Compute the proposals hash for vote config verification.
Future<Uint8List> engineVoteProposalsHash({required String proposalsJson}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineVoteProposalsHash(proposalsJson: proposalsJson);

/// Perform full delegation flow.
Future<List<EngineDelegationResult>> engineVoteDelegate(
        {required String seedPhrase,
        required String voteRoundId,
        required BigInt snapshotHeight,
        required List<int> eaPk,
        required List<int> ncRoot,
        required List<int> nfImtRoot,
        required String pirUrl,
        required int networkId}) =>
    RustLib.instance.api.crateApiEngineApiEngineVoteDelegate(
        seedPhrase: seedPhrase,
        voteRoundId: voteRoundId,
        snapshotHeight: snapshotHeight,
        eaPk: eaPk,
        ncRoot: ncRoot,
        nfImtRoot: nfImtRoot,
        pirUrl: pirUrl,
        networkId: networkId);

/// Build vote commitment (ZKP2) for a single proposal.
Future<EngineVoteCommitment> engineVoteBuildCommitment(
        {required List<int> votingSeed,
        required int networkId,
        required BigInt totalNoteValue,
        required List<int> govCommRand,
        required List<int> votingRoundId,
        required List<int> eaPk,
        required int proposalId,
        required int choice,
        required int numOptions,
        required List<Uint8List> vanAuthPath,
        required int vanPosition,
        required int anchorHeight,
        required BigInt proposalAuthority,
        required bool singleShare}) =>
    RustLib.instance.api.crateApiEngineApiEngineVoteBuildCommitment(
        votingSeed: votingSeed,
        networkId: networkId,
        totalNoteValue: totalNoteValue,
        govCommRand: govCommRand,
        votingRoundId: votingRoundId,
        eaPk: eaPk,
        proposalId: proposalId,
        choice: choice,
        numOptions: numOptions,
        vanAuthPath: vanAuthPath,
        vanPosition: vanPosition,
        anchorHeight: anchorHeight,
        proposalAuthority: proposalAuthority,
        singleShare: singleShare);

/// Propose an Orchard -> Ironwood pool transfer with SpendPolicy restriction.
/// Only spends Orchard notes. Sends to own UA (routed to Ironwood post-NU6.3).
/// Returns (send_amount, fee). Use engine_confirm_send to finalize.
Future<ProposalResult> engineProposePoolTransfer(
        {required BigInt amount, required bool isMax}) =>
    RustLib.instance.api.crateApiEngineApiEngineProposePoolTransfer(
        amount: amount, isMax: isMax);

/// Determine the next migration round action per the Shielded Labs algorithm.
///
/// Returns the action type ("migrate", "consolidate", or "done"),
/// the amount to migrate (if applicable), and consolidation note count.
///
/// Callers: pass the wallet's largest single Orchard note value and total note count.
Future<MigrationRoundResult> engineMigrationNextRound(
        {required BigInt orchardBalanceZat,
        required BigInt largestNoteZat,
        required int noteCount}) =>
    RustLib.instance.api.crateApiEngineApiEngineMigrationNextRound(
        orchardBalanceZat: orchardBalanceZat,
        largestNoteZat: largestNoteZat,
        noteCount: noteCount);

/// Generate a cryptographically random delay (in seconds) for the next round.
/// Uses exponential distribution: D = -600 * log2(U), median = 10 minutes.
Future<double> engineMigrationRandomDelay() =>
    RustLib.instance.api.crateApiEngineApiEngineMigrationRandomDelay();

/// Record a completed migration round to persistent state.
Future<MigrationProgress> engineMigrationRecordRound(
        {required String dataDir,
        required BigInt amountZat,
        required BigInt feeZat,
        required int height}) =>
    RustLib.instance.api.crateApiEngineApiEngineMigrationRecordRound(
        dataDir: dataDir, amountZat: amountZat, feeZat: feeZat, height: height);

/// Plan an Orchard -> Ironwood pool transfer per ZIP 318.
/// Returns a summary with denominations, fees, and duration for user confirmation.
Future<IronwoodPlan> engineIronwoodPlan(
        {required BigInt orchardBalanceZat, required int currentHeight}) =>
    RustLib.instance.api.crateApiEngineApiEngineIronwoodPlan(
        orchardBalanceZat: orchardBalanceZat, currentHeight: currentHeight);

/// Confirm and create the transfer schedule. Returns serialized schedule JSON.
Future<String> engineIronwoodConfirm(
        {required BigInt orchardBalanceZat,
        required int currentHeight,
        required bool torEnabled}) =>
    RustLib.instance.api.crateApiEngineApiEngineIronwoodConfirm(
        orchardBalanceZat: orchardBalanceZat,
        currentHeight: currentHeight,
        torEnabled: torEnabled);

/// Reconcile an in-progress schedule against chain state.
/// Takes the serialized schedule JSON, returns updated JSON + list of invalidated part IDs.
Future<IronwoodReconcileResult> engineIronwoodReconcile(
        {required String scheduleJson,
        required int currentHeight,
        required List<String> confirmedTxids}) =>
    RustLib.instance.api.crateApiEngineApiEngineIronwoodReconcile(
        scheduleJson: scheduleJson,
        currentHeight: currentHeight,
        confirmedTxids: confirmedTxids);

/// Background tick: reconcile + advance schedule. Called from Flutter BGTask or on-foreground.
Future<IronwoodTickResult> engineIronwoodTick(
        {required String dataDir,
        required int currentHeight,
        required List<String> confirmedTxids}) =>
    RustLib.instance.api.crateApiEngineApiEngineIronwoodTick(
        dataDir: dataDir,
        currentHeight: currentHeight,
        confirmedTxids: confirmedTxids);

/// Sign a cast-vote transaction using the voting hotkey.
Future<Uint8List> engineVoteSignCast(
        {required List<int> votingSeed,
        required int networkId,
        required String voteRoundIdHex,
        required List<int> rVpkBytes,
        required List<int> vanNullifier,
        required List<int> voteAuthorityNoteNew,
        required List<int> voteCommitment,
        required int proposalId,
        required int anchorHeight,
        required List<int> alphaV}) =>
    RustLib.instance.api.crateApiEngineApiEngineVoteSignCast(
        votingSeed: votingSeed,
        networkId: networkId,
        voteRoundIdHex: voteRoundIdHex,
        rVpkBytes: rVpkBytes,
        vanNullifier: vanNullifier,
        voteAuthorityNoteNew: voteAuthorityNoteNew,
        voteCommitment: voteCommitment,
        proposalId: proposalId,
        anchorHeight: anchorHeight,
        alphaV: alphaV);

/// Build share payloads for helper server submission.
Future<List<EngineSharePayload>> engineVoteBuildShares(
        {required List<int> sharesHash,
        required int proposalId,
        required int voteDecision,
        required int numOptions,
        required BigInt vcTreePosition,
        required List<Uint8List> encSharesC1,
        required List<Uint8List> encSharesC2,
        required List<int> encSharesIndices,
        required List<Uint8List> shareBlinds,
        required List<Uint8List> shareComms,
        required bool singleShare}) =>
    RustLib.instance.api.crateApiEngineApiEngineVoteBuildShares(
        sharesHash: sharesHash,
        proposalId: proposalId,
        voteDecision: voteDecision,
        numOptions: numOptions,
        vcTreePosition: vcTreePosition,
        encSharesC1: encSharesC1,
        encSharesC2: encSharesC2,
        encSharesIndices: encSharesIndices,
        shareBlinds: shareBlinds,
        shareComms: shareComms,
        singleShare: singleShare);

/// Sync the vote commitment tree and generate VAN witnesses for ZKP2.
Future<List<EngineVanWitness>> engineVoteSyncTreeAndWitness(
        {required String nodeUrl,
        required String voteRoundId,
        required BigInt snapshotHeight,
        required List<int> eaPk,
        required List<int> ncRoot,
        required List<int> nfImtRoot,
        required List<int> vanPositions}) =>
    RustLib.instance.api.crateApiEngineApiEngineVoteSyncTreeAndWitness(
        nodeUrl: nodeUrl,
        voteRoundId: voteRoundId,
        snapshotHeight: snapshotHeight,
        eaPk: eaPk,
        ncRoot: ncRoot,
        nfImtRoot: nfImtRoot,
        vanPositions: vanPositions);

class EngineDelegationResult {
  final Uint8List proof;
  final Uint8List rk;
  final Uint8List nfSigned;
  final Uint8List cmxNew;
  final Uint8List vanComm;
  final Uint8List vanCommRand;
  final List<Uint8List> govNullifiers;
  final Uint8List spendAuthSig;
  final Uint8List sighash;
  final String voteRoundId;
  final BigInt totalValue;
  final Uint8List actionBytes;

  const EngineDelegationResult({
    required this.proof,
    required this.rk,
    required this.nfSigned,
    required this.cmxNew,
    required this.vanComm,
    required this.vanCommRand,
    required this.govNullifiers,
    required this.spendAuthSig,
    required this.sighash,
    required this.voteRoundId,
    required this.totalValue,
    required this.actionBytes,
  });

  @override
  int get hashCode =>
      proof.hashCode ^
      rk.hashCode ^
      nfSigned.hashCode ^
      cmxNew.hashCode ^
      vanComm.hashCode ^
      vanCommRand.hashCode ^
      govNullifiers.hashCode ^
      spendAuthSig.hashCode ^
      sighash.hashCode ^
      voteRoundId.hashCode ^
      totalValue.hashCode ^
      actionBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineDelegationResult &&
          runtimeType == other.runtimeType &&
          proof == other.proof &&
          rk == other.rk &&
          nfSigned == other.nfSigned &&
          cmxNew == other.cmxNew &&
          vanComm == other.vanComm &&
          vanCommRand == other.vanCommRand &&
          govNullifiers == other.govNullifiers &&
          spendAuthSig == other.spendAuthSig &&
          sighash == other.sighash &&
          voteRoundId == other.voteRoundId &&
          totalValue == other.totalValue &&
          actionBytes == other.actionBytes;
}

class EngineEncryptedShare {
  final Uint8List c1;
  final Uint8List c2;
  final int shareIndex;

  const EngineEncryptedShare({
    required this.c1,
    required this.c2,
    required this.shareIndex,
  });

  @override
  int get hashCode => c1.hashCode ^ c2.hashCode ^ shareIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineEncryptedShare &&
          runtimeType == other.runtimeType &&
          c1 == other.c1 &&
          c2 == other.c2 &&
          shareIndex == other.shareIndex;
}

class EngineFrostActionSignature {
  final int actionIndex;
  final String signatureHex;

  const EngineFrostActionSignature({
    required this.actionIndex,
    required this.signatureHex,
  });

  @override
  int get hashCode => actionIndex.hashCode ^ signatureHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostActionSignature &&
          runtimeType == other.runtimeType &&
          actionIndex == other.actionIndex &&
          signatureHex == other.signatureHex;
}

class EngineFrostAggregateResult {
  final String signatureHex;

  const EngineFrostAggregateResult({
    required this.signatureHex,
  });

  @override
  int get hashCode => signatureHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostAggregateResult &&
          runtimeType == other.runtimeType &&
          signatureHex == other.signatureHex;
}

class EngineFrostDkgCompleteResult {
  final int participantId;
  final String keyPackage;
  final String publicKeyPackage;
  final String groupPublicKeyHex;

  const EngineFrostDkgCompleteResult({
    required this.participantId,
    required this.keyPackage,
    required this.publicKeyPackage,
    required this.groupPublicKeyHex,
  });

  @override
  int get hashCode =>
      participantId.hashCode ^
      keyPackage.hashCode ^
      publicKeyPackage.hashCode ^
      groupPublicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostDkgCompleteResult &&
          runtimeType == other.runtimeType &&
          participantId == other.participantId &&
          keyPackage == other.keyPackage &&
          publicKeyPackage == other.publicKeyPackage &&
          groupPublicKeyHex == other.groupPublicKeyHex;
}

class EngineFrostDkgRound1Result {
  final int participantId;
  final String secretPackage;
  final String round1Package;

  const EngineFrostDkgRound1Result({
    required this.participantId,
    required this.secretPackage,
    required this.round1Package,
  });

  @override
  int get hashCode =>
      participantId.hashCode ^ secretPackage.hashCode ^ round1Package.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostDkgRound1Result &&
          runtimeType == other.runtimeType &&
          participantId == other.participantId &&
          secretPackage == other.secretPackage &&
          round1Package == other.round1Package;
}

class EngineFrostDkgRound2Result {
  final String secretPackage;
  final List<EngineFrostParticipantPackage> round2Packages;

  const EngineFrostDkgRound2Result({
    required this.secretPackage,
    required this.round2Packages,
  });

  @override
  int get hashCode => secretPackage.hashCode ^ round2Packages.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostDkgRound2Result &&
          runtimeType == other.runtimeType &&
          secretPackage == other.secretPackage &&
          round2Packages == other.round2Packages;
}

class EngineFrostParticipantPackage {
  final int participantId;
  final String package;

  const EngineFrostParticipantPackage({
    required this.participantId,
    required this.package,
  });

  @override
  int get hashCode => participantId.hashCode ^ package.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostParticipantPackage &&
          runtimeType == other.runtimeType &&
          participantId == other.participantId &&
          package == other.package;
}

class EngineFrostPcztActionRequest {
  final int actionIndex;
  final String sighashHex;
  final String randomizerHex;
  final String randomizerPointHex;

  const EngineFrostPcztActionRequest({
    required this.actionIndex,
    required this.sighashHex,
    required this.randomizerHex,
    required this.randomizerPointHex,
  });

  @override
  int get hashCode =>
      actionIndex.hashCode ^
      sighashHex.hashCode ^
      randomizerHex.hashCode ^
      randomizerPointHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostPcztActionRequest &&
          runtimeType == other.runtimeType &&
          actionIndex == other.actionIndex &&
          sighashHex == other.sighashHex &&
          randomizerHex == other.randomizerHex &&
          randomizerPointHex == other.randomizerPointHex;
}

class EngineFrostPcztSigningRequest {
  final List<EngineFrostPcztActionRequest> orchardActions;

  const EngineFrostPcztSigningRequest({
    required this.orchardActions,
  });

  @override
  int get hashCode => orchardActions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostPcztSigningRequest &&
          runtimeType == other.runtimeType &&
          orchardActions == other.orchardActions;
}

class EngineFrostRandomizerResult {
  final String randomizerHex;
  final String randomizerPointHex;

  const EngineFrostRandomizerResult({
    required this.randomizerHex,
    required this.randomizerPointHex,
  });

  @override
  int get hashCode => randomizerHex.hashCode ^ randomizerPointHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostRandomizerResult &&
          runtimeType == other.runtimeType &&
          randomizerHex == other.randomizerHex &&
          randomizerPointHex == other.randomizerPointHex;
}

class EngineFrostRelayIdentity {
  final String privateKeyHex;
  final String publicKeyHex;

  const EngineFrostRelayIdentity({
    required this.privateKeyHex,
    required this.publicKeyHex,
  });

  @override
  int get hashCode => privateKeyHex.hashCode ^ publicKeyHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostRelayIdentity &&
          runtimeType == other.runtimeType &&
          privateKeyHex == other.privateKeyHex &&
          publicKeyHex == other.publicKeyHex;
}

class EngineFrostRelayLoginProof {
  final String pubkeyHex;
  final String signatureHex;

  const EngineFrostRelayLoginProof({
    required this.pubkeyHex,
    required this.signatureHex,
  });

  @override
  int get hashCode => pubkeyHex.hashCode ^ signatureHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostRelayLoginProof &&
          runtimeType == other.runtimeType &&
          pubkeyHex == other.pubkeyHex &&
          signatureHex == other.signatureHex;
}

class EngineFrostSigningRound1Result {
  final int participantId;
  final String signingNonces;
  final String signingCommitments;

  const EngineFrostSigningRound1Result({
    required this.participantId,
    required this.signingNonces,
    required this.signingCommitments,
  });

  @override
  int get hashCode =>
      participantId.hashCode ^
      signingNonces.hashCode ^
      signingCommitments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostSigningRound1Result &&
          runtimeType == other.runtimeType &&
          participantId == other.participantId &&
          signingNonces == other.signingNonces &&
          signingCommitments == other.signingCommitments;
}

class EngineFrostWalletView {
  final String ufvk;
  final String address;
  final String groupPublicKeyHex;
  final String orchardFvkHex;

  const EngineFrostWalletView({
    required this.ufvk,
    required this.address,
    required this.groupPublicKeyHex,
    required this.orchardFvkHex,
  });

  @override
  int get hashCode =>
      ufvk.hashCode ^
      address.hashCode ^
      groupPublicKeyHex.hashCode ^
      orchardFvkHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineFrostWalletView &&
          runtimeType == other.runtimeType &&
          ufvk == other.ufvk &&
          address == other.address &&
          groupPublicKeyHex == other.groupPublicKeyHex &&
          orchardFvkHex == other.orchardFvkHex;
}

/// A CipherPay invoice as the customer sees it.
///
/// Returned by [`engine_check_invoice`]. Read-only — does not touch the seed
/// and only requires a single anonymous GET to `api.cipherpay.app`.
class EngineInvoice {
  /// CipherPay invoice UUID.
  final String id;

  /// `"pending" | "detected" | "confirmed" | "expired" | "cancelled"`.
  final String status;

  /// Amount priced in ZEC at invoice creation time.
  final double priceZec;

  /// Same amount priced in EUR (CipherPay backs invoices with EUR rates).
  final double priceEur;

  /// Shielded ZEC address the buyer must pay.
  final String paymentAddress;

  /// Memo code in the form `CP-XXXXXXXX`. Buyer's tx must carry this memo
  /// to be auto-detected by CipherPay.
  final String memoCode;

  /// ZEC actually received (set once the tx is detected).
  final double? receivedZec;

  /// Mainnet txid that paid the invoice, once detected.
  final String? detectedTxid;

  /// ISO-8601 expiry timestamp.
  final String expiresAt;

  /// ISO-8601 creation timestamp.
  final String createdAt;

  /// Merchant-supplied product name. May be empty for ad-hoc invoices.
  final String? productName;

  const EngineInvoice({
    required this.id,
    required this.status,
    required this.priceZec,
    required this.priceEur,
    required this.paymentAddress,
    required this.memoCode,
    this.receivedZec,
    this.detectedTxid,
    required this.expiresAt,
    required this.createdAt,
    this.productName,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      status.hashCode ^
      priceZec.hashCode ^
      priceEur.hashCode ^
      paymentAddress.hashCode ^
      memoCode.hashCode ^
      receivedZec.hashCode ^
      detectedTxid.hashCode ^
      expiresAt.hashCode ^
      createdAt.hashCode ^
      productName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineInvoice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          status == other.status &&
          priceZec == other.priceZec &&
          priceEur == other.priceEur &&
          paymentAddress == other.paymentAddress &&
          memoCode == other.memoCode &&
          receivedZec == other.receivedZec &&
          detectedTxid == other.detectedTxid &&
          expiresAt == other.expiresAt &&
          createdAt == other.createdAt &&
          productName == other.productName;
}

/// Info about the recommended LLM model.
class EngineLlmModelInfo {
  final String filename;
  final String displayName;
  final BigInt sizeBytes;

  const EngineLlmModelInfo({
    required this.filename,
    required this.displayName,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      filename.hashCode ^ displayName.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineLlmModelInfo &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          displayName == other.displayName &&
          sizeBytes == other.sizeBytes;
}

/// Multi-chain addresses returned to Dart.
class EngineMultiChainAddresses {
  final String evm;
  final String solana;
  final String bitcoin;

  const EngineMultiChainAddresses({
    required this.evm,
    required this.solana,
    required this.bitcoin,
  });

  @override
  int get hashCode => evm.hashCode ^ solana.hashCode ^ bitcoin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineMultiChainAddresses &&
          runtimeType == other.runtimeType &&
          evm == other.evm &&
          solana == other.solana &&
          bitcoin == other.bitcoin;
}

class EngineSharePayload {
  final Uint8List sharesHash;
  final int proposalId;
  final int voteDecision;
  final Uint8List encShareC1;
  final Uint8List encShareC2;
  final int encShareIndex;
  final BigInt treePosition;
  final Uint8List primaryBlind;

  const EngineSharePayload({
    required this.sharesHash,
    required this.proposalId,
    required this.voteDecision,
    required this.encShareC1,
    required this.encShareC2,
    required this.encShareIndex,
    required this.treePosition,
    required this.primaryBlind,
  });

  @override
  int get hashCode =>
      sharesHash.hashCode ^
      proposalId.hashCode ^
      voteDecision.hashCode ^
      encShareC1.hashCode ^
      encShareC2.hashCode ^
      encShareIndex.hashCode ^
      treePosition.hashCode ^
      primaryBlind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineSharePayload &&
          runtimeType == other.runtimeType &&
          sharesHash == other.sharesHash &&
          proposalId == other.proposalId &&
          voteDecision == other.voteDecision &&
          encShareC1 == other.encShareC1 &&
          encShareC2 == other.encShareC2 &&
          encShareIndex == other.encShareIndex &&
          treePosition == other.treePosition &&
          primaryBlind == other.primaryBlind;
}

class EngineSyncEvent {
  final String eventType;
  final String? phase;
  final int syncedHeight;
  final int latestHeight;
  final int maintenanceQueueLen;
  final String? txid;
  final String? status;
  final String? scope;
  final String? message;
  final BigInt scanProgressNum;
  final BigInt scanProgressDen;
  final BigInt recoveryProgressNum;
  final BigInt recoveryProgressDen;
  final BigInt blocksScanned;
  final BigInt blocksTotal;

  const EngineSyncEvent({
    required this.eventType,
    this.phase,
    required this.syncedHeight,
    required this.latestHeight,
    required this.maintenanceQueueLen,
    this.txid,
    this.status,
    this.scope,
    this.message,
    required this.scanProgressNum,
    required this.scanProgressDen,
    required this.recoveryProgressNum,
    required this.recoveryProgressDen,
    required this.blocksScanned,
    required this.blocksTotal,
  });

  @override
  int get hashCode =>
      eventType.hashCode ^
      phase.hashCode ^
      syncedHeight.hashCode ^
      latestHeight.hashCode ^
      maintenanceQueueLen.hashCode ^
      txid.hashCode ^
      status.hashCode ^
      scope.hashCode ^
      message.hashCode ^
      scanProgressNum.hashCode ^
      scanProgressDen.hashCode ^
      recoveryProgressNum.hashCode ^
      recoveryProgressDen.hashCode ^
      blocksScanned.hashCode ^
      blocksTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineSyncEvent &&
          runtimeType == other.runtimeType &&
          eventType == other.eventType &&
          phase == other.phase &&
          syncedHeight == other.syncedHeight &&
          latestHeight == other.latestHeight &&
          maintenanceQueueLen == other.maintenanceQueueLen &&
          txid == other.txid &&
          status == other.status &&
          scope == other.scope &&
          message == other.message &&
          scanProgressNum == other.scanProgressNum &&
          scanProgressDen == other.scanProgressDen &&
          recoveryProgressNum == other.recoveryProgressNum &&
          recoveryProgressDen == other.recoveryProgressDen &&
          blocksScanned == other.blocksScanned &&
          blocksTotal == other.blocksTotal;
}

/// Sync progress reported to Dart.
class EngineSyncProgress {
  final int syncedHeight;
  final int latestHeight;
  final bool isSyncing;
  final String? connectionError;
  final String? maintenanceError;
  final String phase;
  final int scanningUpTo;
  final int maintenanceQueueLen;
  final BigInt scanProgressNum;
  final BigInt scanProgressDen;
  final BigInt recoveryProgressNum;
  final BigInt recoveryProgressDen;

  /// Blocks scanned this session across every priority (ChainTip,
  /// Historic, FoundNote, Verify). Together with `blocks_total` this is
  /// the user-facing progress signal — it advances smoothly through
  /// ChainTip pre-scan, when `synced_height` is still pinned at the
  /// wallet birthday.
  final BigInt blocksScanned;
  final BigInt blocksTotal;

  const EngineSyncProgress({
    required this.syncedHeight,
    required this.latestHeight,
    required this.isSyncing,
    this.connectionError,
    this.maintenanceError,
    required this.phase,
    required this.scanningUpTo,
    required this.maintenanceQueueLen,
    required this.scanProgressNum,
    required this.scanProgressDen,
    required this.recoveryProgressNum,
    required this.recoveryProgressDen,
    required this.blocksScanned,
    required this.blocksTotal,
  });

  @override
  int get hashCode =>
      syncedHeight.hashCode ^
      latestHeight.hashCode ^
      isSyncing.hashCode ^
      connectionError.hashCode ^
      maintenanceError.hashCode ^
      phase.hashCode ^
      scanningUpTo.hashCode ^
      maintenanceQueueLen.hashCode ^
      scanProgressNum.hashCode ^
      scanProgressDen.hashCode ^
      recoveryProgressNum.hashCode ^
      recoveryProgressDen.hashCode ^
      blocksScanned.hashCode ^
      blocksTotal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineSyncProgress &&
          runtimeType == other.runtimeType &&
          syncedHeight == other.syncedHeight &&
          latestHeight == other.latestHeight &&
          isSyncing == other.isSyncing &&
          connectionError == other.connectionError &&
          maintenanceError == other.maintenanceError &&
          phase == other.phase &&
          scanningUpTo == other.scanningUpTo &&
          maintenanceQueueLen == other.maintenanceQueueLen &&
          scanProgressNum == other.scanProgressNum &&
          scanProgressDen == other.scanProgressDen &&
          recoveryProgressNum == other.recoveryProgressNum &&
          recoveryProgressDen == other.recoveryProgressDen &&
          blocksScanned == other.blocksScanned &&
          blocksTotal == other.blocksTotal;
}

class EngineTransactionRecord {
  final String txid;
  final int height;
  final int timestamp;
  final PlatformInt64 value;
  final String kind;
  final BigInt? fee;
  final String? memo;
  final bool expiredUnmined;

  const EngineTransactionRecord({
    required this.txid,
    required this.height,
    required this.timestamp,
    required this.value,
    required this.kind,
    this.fee,
    this.memo,
    required this.expiredUnmined,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      timestamp.hashCode ^
      value.hashCode ^
      kind.hashCode ^
      fee.hashCode ^
      memo.hashCode ^
      expiredUnmined.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineTransactionRecord &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          timestamp == other.timestamp &&
          value == other.value &&
          kind == other.kind &&
          fee == other.fee &&
          memo == other.memo &&
          expiredUnmined == other.expiredUnmined;
}

class EngineVanWitness {
  final List<Uint8List> authPath;
  final int position;
  final int anchorHeight;

  const EngineVanWitness({
    required this.authPath,
    required this.position,
    required this.anchorHeight,
  });

  @override
  int get hashCode =>
      authPath.hashCode ^ position.hashCode ^ anchorHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineVanWitness &&
          runtimeType == other.runtimeType &&
          authPath == other.authPath &&
          position == other.position &&
          anchorHeight == other.anchorHeight;
}

class EngineVoteCommitment {
  final Uint8List vanNullifier;
  final Uint8List voteAuthorityNoteNew;
  final Uint8List voteCommitment;
  final int proposalId;
  final Uint8List proof;
  final List<EngineEncryptedShare> encShares;
  final int anchorHeight;
  final String voteRoundId;
  final Uint8List sharesHash;
  final List<Uint8List> shareBlinds;
  final List<Uint8List> shareComms;
  final Uint8List rVpkBytes;
  final Uint8List alphaV;

  const EngineVoteCommitment({
    required this.vanNullifier,
    required this.voteAuthorityNoteNew,
    required this.voteCommitment,
    required this.proposalId,
    required this.proof,
    required this.encShares,
    required this.anchorHeight,
    required this.voteRoundId,
    required this.sharesHash,
    required this.shareBlinds,
    required this.shareComms,
    required this.rVpkBytes,
    required this.alphaV,
  });

  @override
  int get hashCode =>
      vanNullifier.hashCode ^
      voteAuthorityNoteNew.hashCode ^
      voteCommitment.hashCode ^
      proposalId.hashCode ^
      proof.hashCode ^
      encShares.hashCode ^
      anchorHeight.hashCode ^
      voteRoundId.hashCode ^
      sharesHash.hashCode ^
      shareBlinds.hashCode ^
      shareComms.hashCode ^
      rVpkBytes.hashCode ^
      alphaV.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineVoteCommitment &&
          runtimeType == other.runtimeType &&
          vanNullifier == other.vanNullifier &&
          voteAuthorityNoteNew == other.voteAuthorityNoteNew &&
          voteCommitment == other.voteCommitment &&
          proposalId == other.proposalId &&
          proof == other.proof &&
          encShares == other.encShares &&
          anchorHeight == other.anchorHeight &&
          voteRoundId == other.voteRoundId &&
          sharesHash == other.sharesHash &&
          shareBlinds == other.shareBlinds &&
          shareComms == other.shareComms &&
          rVpkBytes == other.rVpkBytes &&
          alphaV == other.alphaV;
}

class EngineVotingEligibility {
  /// Total voting weight in zatoshis.
  final BigInt eligibleWeight;

  /// Number of unspent Orchard notes at snapshot.
  final int noteCount;

  /// Number of delegation bundles (max 5 notes each).
  final int bundleCount;

  const EngineVotingEligibility({
    required this.eligibleWeight,
    required this.noteCount,
    required this.bundleCount,
  });

  @override
  int get hashCode =>
      eligibleWeight.hashCode ^ noteCount.hashCode ^ bundleCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineVotingEligibility &&
          runtimeType == other.runtimeType &&
          eligibleWeight == other.eligibleWeight &&
          noteCount == other.noteCount &&
          bundleCount == other.bundleCount;
}

class EngineVotingHotkey {
  final Uint8List secretKey;
  final Uint8List publicKey;
  final String address;

  const EngineVotingHotkey({
    required this.secretKey,
    required this.publicKey,
    required this.address,
  });

  @override
  int get hashCode =>
      secretKey.hashCode ^ publicKey.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineVotingHotkey &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          publicKey == other.publicKey &&
          address == other.address;
}

class EvmFees {
  final BigInt maxPriorityFeePerGas;
  final BigInt maxFeePerGas;

  const EvmFees({
    required this.maxPriorityFeePerGas,
    required this.maxFeePerGas,
  });

  @override
  int get hashCode => maxPriorityFeePerGas.hashCode ^ maxFeePerGas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmFees &&
          runtimeType == other.runtimeType &&
          maxPriorityFeePerGas == other.maxPriorityFeePerGas &&
          maxFeePerGas == other.maxFeePerGas;
}

class EvmReceipt {
  final bool success;
  final BigInt blockNumber;
  final BigInt gasUsed;
  final String txHash;

  const EvmReceipt({
    required this.success,
    required this.blockNumber,
    required this.gasUsed,
    required this.txHash,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      blockNumber.hashCode ^
      gasUsed.hashCode ^
      txHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmReceipt &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          blockNumber == other.blockNumber &&
          gasUsed == other.gasUsed &&
          txHash == other.txHash;
}

/// Swap execution result returned to Dart.
class EvmSwapExecuteResult {
  final String txHash;
  final bool success;
  final BigInt blockNumber;
  final BigInt gasUsed;
  final String srcAmount;
  final String destAmountExpected;

  const EvmSwapExecuteResult({
    required this.txHash,
    required this.success,
    required this.blockNumber,
    required this.gasUsed,
    required this.srcAmount,
    required this.destAmountExpected,
  });

  @override
  int get hashCode =>
      txHash.hashCode ^
      success.hashCode ^
      blockNumber.hashCode ^
      gasUsed.hashCode ^
      srcAmount.hashCode ^
      destAmountExpected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmSwapExecuteResult &&
          runtimeType == other.runtimeType &&
          txHash == other.txHash &&
          success == other.success &&
          blockNumber == other.blockNumber &&
          gasUsed == other.gasUsed &&
          srcAmount == other.srcAmount &&
          destAmountExpected == other.destAmountExpected;
}

/// Quote result returned to Dart.
class EvmSwapQuoteResult {
  final String srcToken;
  final String srcAmount;
  final int srcDecimals;
  final String destToken;
  final String destAmount;
  final int destDecimals;

  /// Serialized JSON of the priceRoute (opaque to Dart, passed back to execute).
  final String priceRouteJson;
  final String tokenTransferProxy;

  const EvmSwapQuoteResult({
    required this.srcToken,
    required this.srcAmount,
    required this.srcDecimals,
    required this.destToken,
    required this.destAmount,
    required this.destDecimals,
    required this.priceRouteJson,
    required this.tokenTransferProxy,
  });

  @override
  int get hashCode =>
      srcToken.hashCode ^
      srcAmount.hashCode ^
      srcDecimals.hashCode ^
      destToken.hashCode ^
      destAmount.hashCode ^
      destDecimals.hashCode ^
      priceRouteJson.hashCode ^
      tokenTransferProxy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmSwapQuoteResult &&
          runtimeType == other.runtimeType &&
          srcToken == other.srcToken &&
          srcAmount == other.srcAmount &&
          srcDecimals == other.srcDecimals &&
          destToken == other.destToken &&
          destAmount == other.destAmount &&
          destDecimals == other.destDecimals &&
          priceRouteJson == other.priceRouteJson &&
          tokenTransferProxy == other.tokenTransferProxy;
}

class IronwoodDenomGroup {
  final BigInt denominationZat;
  final int count;
  final String label;

  const IronwoodDenomGroup({
    required this.denominationZat,
    required this.count,
    required this.label,
  });

  @override
  int get hashCode =>
      denominationZat.hashCode ^ count.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IronwoodDenomGroup &&
          runtimeType == other.runtimeType &&
          denominationZat == other.denominationZat &&
          count == other.count &&
          label == other.label;
}

class IronwoodPlan {
  final BigInt orchardBalanceZat;
  final List<IronwoodDenomGroup> denominations;
  final int totalParts;
  final BigInt totalFeeZat;
  final int estimatedSessions;
  final double estimatedDurationHours;
  final BigInt dustRemainingZat;

  const IronwoodPlan({
    required this.orchardBalanceZat,
    required this.denominations,
    required this.totalParts,
    required this.totalFeeZat,
    required this.estimatedSessions,
    required this.estimatedDurationHours,
    required this.dustRemainingZat,
  });

  @override
  int get hashCode =>
      orchardBalanceZat.hashCode ^
      denominations.hashCode ^
      totalParts.hashCode ^
      totalFeeZat.hashCode ^
      estimatedSessions.hashCode ^
      estimatedDurationHours.hashCode ^
      dustRemainingZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IronwoodPlan &&
          runtimeType == other.runtimeType &&
          orchardBalanceZat == other.orchardBalanceZat &&
          denominations == other.denominations &&
          totalParts == other.totalParts &&
          totalFeeZat == other.totalFeeZat &&
          estimatedSessions == other.estimatedSessions &&
          estimatedDurationHours == other.estimatedDurationHours &&
          dustRemainingZat == other.dustRemainingZat;
}

class IronwoodReconcileResult {
  final String scheduleJson;
  final Uint32List invalidatedIds;
  final bool isComplete;

  const IronwoodReconcileResult({
    required this.scheduleJson,
    required this.invalidatedIds,
    required this.isComplete,
  });

  @override
  int get hashCode =>
      scheduleJson.hashCode ^ invalidatedIds.hashCode ^ isComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IronwoodReconcileResult &&
          runtimeType == other.runtimeType &&
          scheduleJson == other.scheduleJson &&
          invalidatedIds == other.invalidatedIds &&
          isComplete == other.isComplete;
}

class IronwoodTickResult {
  final int partsBroadcast;
  final int partsConfirmed;
  final int partsInvalidated;
  final bool isComplete;
  final int? nextBroadcastHeight;

  const IronwoodTickResult({
    required this.partsBroadcast,
    required this.partsConfirmed,
    required this.partsInvalidated,
    required this.isComplete,
    this.nextBroadcastHeight,
  });

  @override
  int get hashCode =>
      partsBroadcast.hashCode ^
      partsConfirmed.hashCode ^
      partsInvalidated.hashCode ^
      isComplete.hashCode ^
      nextBroadcastHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IronwoodTickResult &&
          runtimeType == other.runtimeType &&
          partsBroadcast == other.partsBroadcast &&
          partsConfirmed == other.partsConfirmed &&
          partsInvalidated == other.partsInvalidated &&
          isComplete == other.isComplete &&
          nextBroadcastHeight == other.nextBroadcastHeight;
}

class MigrationProgress {
  final int roundsCompleted;
  final BigInt totalMigratedZat;
  final BigInt totalFeesZat;

  const MigrationProgress({
    required this.roundsCompleted,
    required this.totalMigratedZat,
    required this.totalFeesZat,
  });

  @override
  int get hashCode =>
      roundsCompleted.hashCode ^
      totalMigratedZat.hashCode ^
      totalFeesZat.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationProgress &&
          runtimeType == other.runtimeType &&
          roundsCompleted == other.roundsCompleted &&
          totalMigratedZat == other.totalMigratedZat &&
          totalFeesZat == other.totalFeesZat;
}

class MigrationRoundResult {
  final String action;
  final BigInt amountZat;
  final int consolidateCount;

  const MigrationRoundResult({
    required this.action,
    required this.amountZat,
    required this.consolidateCount,
  });

  @override
  int get hashCode =>
      action.hashCode ^ amountZat.hashCode ^ consolidateCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MigrationRoundResult &&
          runtimeType == other.runtimeType &&
          action == other.action &&
          amountZat == other.amountZat &&
          consolidateCount == other.consolidateCount;
}

class PolymarketAuthResult {
  final String address;
  final String signature;

  const PolymarketAuthResult({
    required this.address,
    required this.signature,
  });

  @override
  int get hashCode => address.hashCode ^ signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PolymarketAuthResult &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          signature == other.signature;
}

/// Proposal result returned to Dart.
class ProposalResult {
  final BigInt sendAmount;
  final BigInt fee;
  final bool isExact;

  const ProposalResult({
    required this.sendAmount,
    required this.fee,
    required this.isExact,
  });

  @override
  int get hashCode => sendAmount.hashCode ^ fee.hashCode ^ isExact.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalResult &&
          runtimeType == other.runtimeType &&
          sendAmount == other.sendAmount &&
          fee == other.fee &&
          isExact == other.isExact;
}
