// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'wallet.dart';

// These functions are ignored because they are not marked as `pub`: `to_network`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// Create a new wallet. Returns the 24-word seed phrase.
Future<String> engineCreateWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required int chainHeight,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineCreateWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        chainHeight: chainHeight,
        dbCipherKey: dbCipherKey);

/// Restore a wallet from a BIP39 seed phrase.
Future<void> engineRestoreFromSeed(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String seedPhrase,
        required int birthday,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineRestoreFromSeed(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        seedPhrase: seedPhrase,
        birthday: birthday,
        dbCipherKey: dbCipherKey);

/// Restore a watch-only wallet from a UFVK.
Future<void> engineRestoreFromUfvk(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String ufvk,
        required int birthday,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineRestoreFromUfvk(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        ufvk: ufvk,
        birthday: birthday,
        dbCipherKey: dbCipherKey);

/// Open an existing wallet from disk.
Future<void> engineOpenWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        String? dbCipherKey}) =>
    RustLib.instance.api.crateApiEngineApiEngineOpenWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        dbCipherKey: dbCipherKey);

/// Close the current wallet.
Future<void> engineCloseWallet() =>
    RustLib.instance.api.crateApiEngineApiEngineCloseWallet();

/// Delete wallet database files from disk.
Future<void> engineDeleteWalletData({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineDeleteWalletData(dataDir: dataDir);

Future<List<AddressInfo>> engineGetAddresses() =>
    RustLib.instance.api.crateApiEngineApiEngineGetAddresses();

Future<List<String>> engineGetTransparentAddresses() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransparentAddresses();

Future<WalletBalance> engineGetWalletBalance() =>
    RustLib.instance.api.crateApiEngineApiEngineGetWalletBalance();

/// Returns the maximum amount (in zatoshis) that can be sent to the given
/// address after accounting for the exact ZIP-317 fee.
Future<BigInt> engineGetMaxSendable({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetMaxSendable(address: address);

Future<int> engineGetBirthday() =>
    RustLib.instance.api.crateApiEngineApiEngineGetBirthday();

Future<int> engineGetWalletSyncedHeight() =>
    RustLib.instance.api.crateApiEngineApiEngineGetWalletSyncedHeight();

/// Native balance in raw wei as decimal string.
Future<String> engineGetNativeBalance(
        {required String rpcUrl, required String address}) =>
    RustLib.instance.api.crateApiEngineApiEngineGetNativeBalance(
        rpcUrl: rpcUrl, address: address);

/// ERC-20 balance in raw token units as decimal string.
Future<String> engineGetErc20Balance(
        {required String rpcUrl,
        required String tokenContract,
        required String ownerAddress}) =>
    RustLib.instance.api.crateApiEngineApiEngineGetErc20Balance(
        rpcUrl: rpcUrl,
        tokenContract: tokenContract,
        ownerAddress: ownerAddress);

/// Pending nonce for an address.
Future<BigInt> engineGetNonce(
        {required String rpcUrl, required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetNonce(rpcUrl: rpcUrl, address: address);

/// Suggested EIP-1559 gas fees. Returns (maxPriorityFeePerGas, maxFeePerGas) in wei.
Future<EvmFees> engineSuggestEip1559Fees(
        {required String rpcUrl, required BigInt chainId}) =>
    RustLib.instance.api.crateApiEngineApiEngineSuggestEip1559Fees(
        rpcUrl: rpcUrl, chainId: chainId);

/// ERC-20 approve: sign + broadcast + wait. Returns tx hash.
Future<String> engineApproveErc20(
        {required String rpcUrl,
        required String seedPhrase,
        required String ownerAddress,
        required String tokenAddress,
        required String spenderAddress,
        required String amountRaw,
        required BigInt chainId}) =>
    RustLib.instance.api.crateApiEngineApiEngineApproveErc20(
        rpcUrl: rpcUrl,
        seedPhrase: seedPhrase,
        ownerAddress: ownerAddress,
        tokenAddress: tokenAddress,
        spenderAddress: spenderAddress,
        amountRaw: amountRaw,
        chainId: chainId);

/// Wait for a tx receipt. Returns (success, block_number).
Future<EvmReceipt> engineWaitForReceipt(
        {required String rpcUrl, required String txHash}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineWaitForReceipt(rpcUrl: rpcUrl, txHash: txHash);

/// ERC-1155 isApprovedForAll check.
Future<bool> engineErc1155IsApprovedForAll(
        {required String rpcUrl,
        required String owner,
        required String tokenContract,
        required String operator_}) =>
    RustLib.instance.api.crateApiEngineApiEngineErc1155IsApprovedForAll(
        rpcUrl: rpcUrl,
        owner: owner,
        tokenContract: tokenContract,
        operator_: operator_);

/// ERC-1155 setApprovalForAll: sign + broadcast + wait. Returns tx hash.
Future<String> engineErc1155SetApprovalForAll(
        {required String rpcUrl,
        required String seedPhrase,
        required String ownerAddress,
        required String tokenContract,
        required String operator_,
        required bool approved,
        required BigInt chainId}) =>
    RustLib.instance.api.crateApiEngineApiEngineErc1155SetApprovalForAll(
        rpcUrl: rpcUrl,
        seedPhrase: seedPhrase,
        ownerAddress: ownerAddress,
        tokenContract: tokenContract,
        operator_: operator_,
        approved: approved,
        chainId: chainId);

Future<bool> engineHasSpendingKey() =>
    RustLib.instance.api.crateApiEngineApiEngineHasSpendingKey();

Future<String?> engineExportUfvk() =>
    RustLib.instance.api.crateApiEngineApiEngineExportUfvk();

Future<AddressValidation> engineValidateAddress({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineValidateAddress(address: address);

Future<bool> engineValidateSeed({required String seed}) =>
    RustLib.instance.api.crateApiEngineApiEngineValidateSeed(seed: seed);

Future<int> engineGetLatestBlockHeight({required String serverUrl}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetLatestBlockHeight(serverUrl: serverUrl);

Future<void> engineStartSync() =>
    RustLib.instance.api.crateApiEngineApiEngineStartSync();

Future<void> engineStopSync() =>
    RustLib.instance.api.crateApiEngineApiEngineStopSync();

/// Rescan the wallet from its birthday height by truncating and restarting sync.
Future<void> engineRescanFromBirthday() =>
    RustLib.instance.api.crateApiEngineApiEngineRescanFromBirthday();

Future<EngineSyncProgress> engineGetSyncProgress() =>
    RustLib.instance.api.crateApiEngineApiEngineGetSyncProgress();

Future<void> engineRegisterInactiveWallet({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineRegisterInactiveWallet(dataDir: dataDir);

Future<void> engineUnregisterInactiveWallet({required String dataDir}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineUnregisterInactiveWallet(dataDir: dataDir);

Future<void> engineClearInactiveWallets() =>
    RustLib.instance.api.crateApiEngineApiEngineClearInactiveWallets();

/// Step 1: Create a proposal and return exact fee info.
/// When `is_max` is true, `amount` is ignored and the SDK computes the max sendable.
Future<ProposalResult> engineProposeSend(
        {required String address,
        required BigInt amount,
        String? memo,
        required bool isMax}) =>
    RustLib.instance.api.crateApiEngineApiEngineProposeSend(
        address: address, amount: amount, memo: memo, isMax: isMax);

/// Step 2: Confirm and broadcast the previously proposed transaction.
Future<String> engineConfirmSend({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineConfirmSend(seedPhrase: seedPhrase);

/// Legacy single-step send (still used for multi-recipient or fallback).
Future<String> engineSendPayment(
        {required String seedPhrase,
        required String address,
        required BigInt amount,
        String? memo}) =>
    RustLib.instance.api.crateApiEngineApiEngineSendPayment(
        seedPhrase: seedPhrase, address: address, amount: amount, memo: memo);

/// Shield transparent funds into the shielded pool.
Future<String> engineShieldFunds({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineShieldFunds(seedPhrase: seedPhrase);

Future<List<EngineTransactionRecord>> engineGetTransactions() =>
    RustLib.instance.api.crateApiEngineApiEngineGetTransactions();

Future<List<MarketInfo>> engineGetMarkets(
        {String? keyword, required int limit}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineGetMarkets(keyword: keyword, limit: limit);

Future<TradeSignalInfo?> engineAnalyzeOpportunity(
        {required BigInt marketId,
        required int outcomeIndex,
        required double estimatedProb,
        required double confidence,
        required double bankroll,
        required double maxBet}) =>
    RustLib.instance.api.crateApiEngineApiEngineAnalyzeOpportunity(
        marketId: marketId,
        outcomeIndex: outcomeIndex,
        estimatedProb: estimatedProb,
        confidence: confidence,
        bankroll: bankroll,
        maxBet: maxBet);

/// Derive the EVM (BSC/ETH) address from the wallet's BIP-39 seed phrase.
/// Uses the standard BIP-44 path m/44'/60'/0'/0/0.
Future<String> engineDeriveEvmAddress({required String seedPhrase}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineDeriveEvmAddress(seedPhrase: seedPhrase);

/// Derive addresses for EVM, Solana, and Bitcoin from a single seed phrase.
/// All derivation is CPU-only (no network calls).
Future<EngineMultiChainAddresses> engineDeriveMultiChainAddresses(
        {required String seedPhrase}) =>
    RustLib.instance.api.crateApiEngineApiEngineDeriveMultiChainAddresses(
        seedPhrase: seedPhrase);

/// Sign an unsigned EVM transaction and return the broadcast-ready signed bytes.
Future<String> engineSignEvmTx(
        {required String seedPhrase, required String unsignedTxHex}) =>
    RustLib.instance.api.crateApiEngineApiEngineSignEvmTx(
        seedPhrase: seedPhrase, unsignedTxHex: unsignedTxHex);

/// Sign an unsigned EVM transaction, broadcast it via JSON-RPC, and return the tx hash.
Future<String> engineSignAndBroadcastEvmTx(
        {required String seedPhrase,
        required String unsignedTxHex,
        required String rpcUrl}) =>
    RustLib.instance.api.crateApiEngineApiEngineSignAndBroadcastEvmTx(
        seedPhrase: seedPhrase, unsignedTxHex: unsignedTxHex, rpcUrl: rpcUrl);

/// Load a GGUF model and tokenizer from the given file paths.
/// Must be called before `engine_llm_infer`. Blocks while loading (~1-5s).
Future<void> engineLlmLoad(
        {required String modelPath, required String tokenizerPath}) =>
    RustLib.instance.api.crateApiEngineApiEngineLlmLoad(
        modelPath: modelPath, tokenizerPath: tokenizerPath);

/// Unload the LLM from memory.
Future<void> engineLlmUnload() =>
    RustLib.instance.api.crateApiEngineApiEngineLlmUnload();

/// Check if an LLM model is currently loaded.
Future<bool> engineLlmIsLoaded() =>
    RustLib.instance.api.crateApiEngineApiEngineLlmIsLoaded();

/// Run LLM inference on a raw prompt. Returns the generated text.
Future<String> engineLlmInfer(
        {required String prompt,
        required int maxTokens,
        required double temperature}) =>
    RustLib.instance.api.crateApiEngineApiEngineLlmInfer(
        prompt: prompt, maxTokens: maxTokens, temperature: temperature);

/// Build an intent-classification prompt from the user's natural language input.
/// The returned prompt is ready to pass to `engine_llm_infer`.
Future<String> engineLlmBuildIntentPrompt({required String userInput}) =>
    RustLib.instance.api
        .crateApiEngineApiEngineLlmBuildIntentPrompt(userInput: userInput);

/// Get the recommended model filename, display name, and expected size in bytes.
Future<EngineLlmModelInfo> engineLlmRecommendedModel() =>
    RustLib.instance.api.crateApiEngineApiEngineLlmRecommendedModel();

/// Sign the CLOB L1 auth message to derive API credentials.
/// Returns (polygon_address, eip712_signature_hex).
Future<PolymarketAuthResult> enginePolymarketSignAuth(
        {required String seedPhrase,
        required BigInt timestamp,
        required BigInt nonce}) =>
    RustLib.instance.api.crateApiEngineApiEnginePolymarketSignAuth(
        seedPhrase: seedPhrase, timestamp: timestamp, nonce: nonce);

/// Sign a Polymarket CLOB V2 order with EIP-712.
/// Returns the hex-encoded signature.
Future<String> enginePolymarketSignOrder(
        {required String seedPhrase,
        required String salt,
        required String maker,
        required String signer,
        required String tokenId,
        required String makerAmount,
        required String takerAmount,
        required int side,
        required int signatureType,
        required String timestamp,
        required String metadata,
        required String builder,
        required bool negRisk}) =>
    RustLib.instance.api.crateApiEngineApiEnginePolymarketSignOrder(
        seedPhrase: seedPhrase,
        salt: salt,
        maker: maker,
        signer: signer,
        tokenId: tokenId,
        makerAmount: makerAmount,
        takerAmount: takerAmount,
        side: side,
        signatureType: signatureType,
        timestamp: timestamp,
        metadata: metadata,
        builder: builder,
        negRisk: negRisk);

/// Whether one Gamma `/markets` or nested event market object passes the default
/// tradability filter (same rules as `zipher-cli polymarket list`). Pure JSON — no wallet.
Future<bool> enginePolymarketGammaMarketPassesQualityFilter(
        {required String marketJson, required bool relaxed}) =>
    RustLib.instance.api
        .crateApiEngineApiEnginePolymarketGammaMarketPassesQualityFilter(
            marketJson: marketJson, relaxed: relaxed);

/// Polymarket discovery: Gamma events + Rust grouping/quality (same as CLI `polymarket list`).
/// Returns JSON `PolymarketDiscoverySummary`.
Future<String> enginePolymarketDiscover(
        {String? keyword, required int limit}) =>
    RustLib.instance.api.crateApiEngineApiEnginePolymarketDiscover(
        keyword: keyword, limit: limit);

/// Polymarket open positions for `user` (0x + 40 hex) via public Data API.
/// Returns JSON array of `PolymarketPosition`.
Future<String> enginePolymarketGetPositions({required String address}) =>
    RustLib.instance.api
        .crateApiEngineApiEnginePolymarketGetPositions(address: address);

/// Get a ParaSwap quote for a same-chain EVM swap.
Future<EvmSwapQuoteResult> engineEvmSwapQuote(
        {required BigInt chainId,
        required String srcToken,
        required int srcDecimals,
        required String destToken,
        required int destDecimals,
        required String amountRaw,
        required String userAddress}) =>
    RustLib.instance.api.crateApiEngineApiEngineEvmSwapQuote(
        chainId: chainId,
        srcToken: srcToken,
        srcDecimals: srcDecimals,
        destToken: destToken,
        destDecimals: destDecimals,
        amountRaw: amountRaw,
        userAddress: userAddress);

/// Execute a full same-chain EVM swap: quote -> approve (if ERC-20) -> build -> sign -> broadcast -> wait.
/// All RLP encoding, signing, and broadcasting happens in Rust.
Future<EvmSwapExecuteResult> engineEvmSwapExecute(
        {required String rpcUrl,
        required String seedPhrase,
        required BigInt chainId,
        required String userAddress,
        required String srcToken,
        required int srcDecimals,
        required String destToken,
        required int destDecimals,
        required String amountRaw,
        required int slippageBps}) =>
    RustLib.instance.api.crateApiEngineApiEngineEvmSwapExecute(
        rpcUrl: rpcUrl,
        seedPhrase: seedPhrase,
        chainId: chainId,
        userAddress: userAddress,
        srcToken: srcToken,
        srcDecimals: srcDecimals,
        destToken: destToken,
        destDecimals: destDecimals,
        amountRaw: amountRaw,
        slippageBps: slippageBps);

/// Info about the recommended LLM model.
class EngineLlmModelInfo {
  final String filename;
  final String displayName;
  final BigInt sizeBytes;

  const EngineLlmModelInfo({
    required this.filename,
    required this.displayName,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      filename.hashCode ^ displayName.hashCode ^ sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineLlmModelInfo &&
          runtimeType == other.runtimeType &&
          filename == other.filename &&
          displayName == other.displayName &&
          sizeBytes == other.sizeBytes;
}

/// Multi-chain addresses returned to Dart.
class EngineMultiChainAddresses {
  final String evm;
  final String solana;
  final String bitcoin;

  const EngineMultiChainAddresses({
    required this.evm,
    required this.solana,
    required this.bitcoin,
  });

  @override
  int get hashCode => evm.hashCode ^ solana.hashCode ^ bitcoin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineMultiChainAddresses &&
          runtimeType == other.runtimeType &&
          evm == other.evm &&
          solana == other.solana &&
          bitcoin == other.bitcoin;
}

/// Sync progress reported to Dart.
class EngineSyncProgress {
  final int syncedHeight;
  final int latestHeight;
  final bool isSyncing;
  final String? connectionError;
  final int scanningUpTo;

  const EngineSyncProgress({
    required this.syncedHeight,
    required this.latestHeight,
    required this.isSyncing,
    this.connectionError,
    required this.scanningUpTo,
  });

  @override
  int get hashCode =>
      syncedHeight.hashCode ^
      latestHeight.hashCode ^
      isSyncing.hashCode ^
      connectionError.hashCode ^
      scanningUpTo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineSyncProgress &&
          runtimeType == other.runtimeType &&
          syncedHeight == other.syncedHeight &&
          latestHeight == other.latestHeight &&
          isSyncing == other.isSyncing &&
          connectionError == other.connectionError &&
          scanningUpTo == other.scanningUpTo;
}

class EngineTransactionRecord {
  final String txid;
  final int height;
  final int timestamp;
  final PlatformInt64 value;
  final String kind;
  final BigInt? fee;
  final String? memo;
  final bool expiredUnmined;

  const EngineTransactionRecord({
    required this.txid,
    required this.height,
    required this.timestamp,
    required this.value,
    required this.kind,
    this.fee,
    this.memo,
    required this.expiredUnmined,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      height.hashCode ^
      timestamp.hashCode ^
      value.hashCode ^
      kind.hashCode ^
      fee.hashCode ^
      memo.hashCode ^
      expiredUnmined.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EngineTransactionRecord &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          height == other.height &&
          timestamp == other.timestamp &&
          value == other.value &&
          kind == other.kind &&
          fee == other.fee &&
          memo == other.memo &&
          expiredUnmined == other.expiredUnmined;
}

class EvmFees {
  final BigInt maxPriorityFeePerGas;
  final BigInt maxFeePerGas;

  const EvmFees({
    required this.maxPriorityFeePerGas,
    required this.maxFeePerGas,
  });

  @override
  int get hashCode => maxPriorityFeePerGas.hashCode ^ maxFeePerGas.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmFees &&
          runtimeType == other.runtimeType &&
          maxPriorityFeePerGas == other.maxPriorityFeePerGas &&
          maxFeePerGas == other.maxFeePerGas;
}

class EvmReceipt {
  final bool success;
  final BigInt blockNumber;
  final BigInt gasUsed;
  final String txHash;

  const EvmReceipt({
    required this.success,
    required this.blockNumber,
    required this.gasUsed,
    required this.txHash,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      blockNumber.hashCode ^
      gasUsed.hashCode ^
      txHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmReceipt &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          blockNumber == other.blockNumber &&
          gasUsed == other.gasUsed &&
          txHash == other.txHash;
}

/// Swap execution result returned to Dart.
class EvmSwapExecuteResult {
  final String txHash;
  final bool success;
  final BigInt blockNumber;
  final BigInt gasUsed;
  final String srcAmount;
  final String destAmountExpected;

  const EvmSwapExecuteResult({
    required this.txHash,
    required this.success,
    required this.blockNumber,
    required this.gasUsed,
    required this.srcAmount,
    required this.destAmountExpected,
  });

  @override
  int get hashCode =>
      txHash.hashCode ^
      success.hashCode ^
      blockNumber.hashCode ^
      gasUsed.hashCode ^
      srcAmount.hashCode ^
      destAmountExpected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmSwapExecuteResult &&
          runtimeType == other.runtimeType &&
          txHash == other.txHash &&
          success == other.success &&
          blockNumber == other.blockNumber &&
          gasUsed == other.gasUsed &&
          srcAmount == other.srcAmount &&
          destAmountExpected == other.destAmountExpected;
}

/// Quote result returned to Dart.
class EvmSwapQuoteResult {
  final String srcToken;
  final String srcAmount;
  final int srcDecimals;
  final String destToken;
  final String destAmount;
  final int destDecimals;

  /// Serialized JSON of the priceRoute (opaque to Dart, passed back to execute).
  final String priceRouteJson;
  final String tokenTransferProxy;

  const EvmSwapQuoteResult({
    required this.srcToken,
    required this.srcAmount,
    required this.srcDecimals,
    required this.destToken,
    required this.destAmount,
    required this.destDecimals,
    required this.priceRouteJson,
    required this.tokenTransferProxy,
  });

  @override
  int get hashCode =>
      srcToken.hashCode ^
      srcAmount.hashCode ^
      srcDecimals.hashCode ^
      destToken.hashCode ^
      destAmount.hashCode ^
      destDecimals.hashCode ^
      priceRouteJson.hashCode ^
      tokenTransferProxy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvmSwapQuoteResult &&
          runtimeType == other.runtimeType &&
          srcToken == other.srcToken &&
          srcAmount == other.srcAmount &&
          srcDecimals == other.srcDecimals &&
          destToken == other.destToken &&
          destAmount == other.destAmount &&
          destDecimals == other.destDecimals &&
          priceRouteJson == other.priceRouteJson &&
          tokenTransferProxy == other.tokenTransferProxy;
}

class MarketInfo {
  final BigInt id;
  final String title;
  final String? description;
  final String? state;
  final List<MarketOutcome> outcomes;

  const MarketInfo({
    required this.id,
    required this.title,
    this.description,
    this.state,
    required this.outcomes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      description.hashCode ^
      state.hashCode ^
      outcomes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          description == other.description &&
          state == other.state &&
          outcomes == other.outcomes;
}

class MarketOutcome {
  final String title;
  final double price;
  final BigInt? outcomeId;

  const MarketOutcome({
    required this.title,
    required this.price,
    this.outcomeId,
  });

  @override
  int get hashCode => title.hashCode ^ price.hashCode ^ outcomeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MarketOutcome &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          price == other.price &&
          outcomeId == other.outcomeId;
}

class PolymarketAuthResult {
  final String address;
  final String signature;

  const PolymarketAuthResult({
    required this.address,
    required this.signature,
  });

  @override
  int get hashCode => address.hashCode ^ signature.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PolymarketAuthResult &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          signature == other.signature;
}

/// Proposal result returned to Dart.
class ProposalResult {
  final BigInt sendAmount;
  final BigInt fee;
  final bool isExact;

  const ProposalResult({
    required this.sendAmount,
    required this.fee,
    required this.isExact,
  });

  @override
  int get hashCode => sendAmount.hashCode ^ fee.hashCode ^ isExact.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProposalResult &&
          runtimeType == other.runtimeType &&
          sendAmount == other.sendAmount &&
          fee == other.fee &&
          isExact == other.isExact;
}

class TradeSignalInfo {
  final BigInt marketId;
  final String marketTitle;
  final int outcomeIndex;
  final String outcomeTitle;
  final double marketProb;
  final double estimatedProb;
  final double edge;
  final double kellyFraction;
  final double recommendedBetUsdt;
  final double expectedValue;
  final double confidence;
  final String reason;

  const TradeSignalInfo({
    required this.marketId,
    required this.marketTitle,
    required this.outcomeIndex,
    required this.outcomeTitle,
    required this.marketProb,
    required this.estimatedProb,
    required this.edge,
    required this.kellyFraction,
    required this.recommendedBetUsdt,
    required this.expectedValue,
    required this.confidence,
    required this.reason,
  });

  @override
  int get hashCode =>
      marketId.hashCode ^
      marketTitle.hashCode ^
      outcomeIndex.hashCode ^
      outcomeTitle.hashCode ^
      marketProb.hashCode ^
      estimatedProb.hashCode ^
      edge.hashCode ^
      kellyFraction.hashCode ^
      recommendedBetUsdt.hashCode ^
      expectedValue.hashCode ^
      confidence.hashCode ^
      reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TradeSignalInfo &&
          runtimeType == other.runtimeType &&
          marketId == other.marketId &&
          marketTitle == other.marketTitle &&
          outcomeIndex == other.outcomeIndex &&
          outcomeTitle == other.outcomeTitle &&
          marketProb == other.marketProb &&
          estimatedProb == other.estimatedProb &&
          edge == other.edge &&
          kellyFraction == other.kellyFraction &&
          recommendedBetUsdt == other.recommendedBetUsdt &&
          expectedValue == other.expectedValue &&
          confidence == other.confidence &&
          reason == other.reason;
}
