// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'wallet.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_config`, `build_transaction_request`, `zat_to_u64`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CLIENT`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `deref`, `initialize`

/// Create a brand-new wallet from fresh entropy.
/// Returns the 24-word seed phrase.
Future<String> createWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required int chainHeight}) =>
    RustLib.instance.api.crateApiWalletCreateWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        chainHeight: chainHeight);

/// Restore a wallet from a seed phrase.
Future<void> restoreFromSeed(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String seedPhrase,
        required int birthday}) =>
    RustLib.instance.api.crateApiWalletRestoreFromSeed(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        seedPhrase: seedPhrase,
        birthday: birthday);

/// Restore a wallet from a unified full viewing key (watch-only).
Future<void> restoreFromUfvk(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String ufvk,
        required int birthday}) =>
    RustLib.instance.api.crateApiWalletRestoreFromUfvk(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        ufvk: ufvk,
        birthday: birthday);

/// Open an existing wallet from disk.
Future<void> openWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType}) =>
    RustLib.instance.api.crateApiWalletOpenWallet(
        dataDir: dataDir, serverUrl: serverUrl, chainType: chainType);

/// Save the wallet to disk and release resources.
Future<void> closeWallet() => RustLib.instance.api.crateApiWalletCloseWallet();

/// Start syncing and await completion.
Future<SyncResultInfo> syncWallet() =>
    RustLib.instance.api.crateApiWalletSyncWallet();

/// Start syncing without awaiting (runs in background).
Future<void> startSync() => RustLib.instance.api.crateApiWalletStartSync();

/// Pause a running sync.
Future<void> pauseSync() => RustLib.instance.api.crateApiWalletPauseSync();

/// Resume a paused sync.
Future<void> resumeSync() => RustLib.instance.api.crateApiWalletResumeSync();

/// Stop a running sync.
Future<void> stopSync() => RustLib.instance.api.crateApiWalletStopSync();

/// Full rescan from wallet birthday.
Future<SyncResultInfo> rescanWallet() =>
    RustLib.instance.api.crateApiWalletRescanWallet();

/// Get current sync status without blocking.
Future<SyncStatusInfo> getSyncStatus() =>
    RustLib.instance.api.crateApiWalletGetSyncStatus();

/// Returns pool balances for the default account.
Future<WalletBalance> getWalletBalance() =>
    RustLib.instance.api.crateApiWalletGetWalletBalance();

/// Get the wallet's unified addresses.
Future<List<AddressInfo>> getAddresses() =>
    RustLib.instance.api.crateApiWalletGetAddresses();

/// Get the wallet's transparent addresses.
Future<List<String>> getTransparentAddresses() =>
    RustLib.instance.api.crateApiWalletGetTransparentAddresses();

/// Get transaction summaries.
Future<List<TransactionRecord>> getTransactions() =>
    RustLib.instance.api.crateApiWalletGetTransactions();

/// Get detailed value transfers (per-recipient breakdown with memos).
Future<List<ValueTransferRecord>> getValueTransfers() =>
    RustLib.instance.api.crateApiWalletGetValueTransfers();

/// Search for messages (memo-bearing value transfers) optionally filtered by text.
Future<List<ValueTransferRecord>> getMessages({String? filter}) =>
    RustLib.instance.api.crateApiWalletGetMessages(filter: filter);

/// Send ZEC to one or more recipients.
Future<String> sendPayment({required List<PaymentRecipient> recipients}) =>
    RustLib.instance.api.crateApiWalletSendPayment(recipients: recipients);

/// Shield transparent funds to the best shielded pool.
Future<String> shieldFunds() =>
    RustLib.instance.api.crateApiWalletShieldFunds();

/// Validate a Zcash address and return its type.
Future<AddressValidation> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiWalletValidateAddress(address: address);

/// Validate a seed phrase.
Future<bool> validateSeed({required String seed}) =>
    RustLib.instance.api.crateApiWalletValidateSeed(seed: seed);

/// Get server info as JSON string.
Future<String> getServerInfo() =>
    RustLib.instance.api.crateApiWalletGetServerInfo();

/// Update the lightwalletd server URL.
Future<void> setServer({required String serverUrl}) =>
    RustLib.instance.api.crateApiWalletSetServer(serverUrl: serverUrl);

/// Get the wallet's seed phrase.
/// Returns None for watch-only wallets.
Future<String?> getSeedPhrase() =>
    RustLib.instance.api.crateApiWalletGetSeedPhrase();

/// Get the wallet's birthday height.
Future<int> getBirthday() => RustLib.instance.api.crateApiWalletGetBirthday();

/// Export the wallet's unified full viewing key (UFVK).
/// Safe to share -- allows watching the wallet but not spending.
Future<String?> exportUfvk() => RustLib.instance.api.crateApiWalletExportUfvk();

/// Check whether this wallet has spending capability (vs watch-only).
Future<bool> hasSpendingKey() =>
    RustLib.instance.api.crateApiWalletHasSpendingKey();

/// Delete wallet data from disk. Must be called after close_wallet().
Future<void> deleteWalletData({required String dataDir}) =>
    RustLib.instance.api.crateApiWalletDeleteWalletData(dataDir: dataDir);

/// Start the periodic save task (saves wallet state to disk at checkpoints).
Future<void> startSaveTask() =>
    RustLib.instance.api.crateApiWalletStartSaveTask();

@freezed
sealed class AddressInfo with _$AddressInfo {
  const factory AddressInfo({
    required String address,
    required bool hasTransparent,
    required bool hasSapling,
    required bool hasOrchard,
  }) = _AddressInfo;
}

@freezed
sealed class AddressValidation with _$AddressValidation {
  const factory AddressValidation({
    required bool isValid,
    String? addressType,
  }) = _AddressValidation;
}

enum ChainType {
  mainnet,
  testnet,
  ;
}

@freezed
sealed class PaymentRecipient with _$PaymentRecipient {
  const factory PaymentRecipient({
    required String address,
    required BigInt amount,
    String? memo,
  }) = _PaymentRecipient;
}

@freezed
sealed class SyncResultInfo with _$SyncResultInfo {
  const factory SyncResultInfo({
    required int startHeight,
    required int endHeight,
    required int blocksScanned,
  }) = _SyncResultInfo;
}

@freezed
sealed class SyncStatusInfo with _$SyncStatusInfo {
  const factory SyncStatusInfo({
    required String mode,
  }) = _SyncStatusInfo;
}

@freezed
sealed class TransactionRecord with _$TransactionRecord {
  const factory TransactionRecord({
    required String txid,
    required int height,
    required BigInt timestamp,
    required PlatformInt64 value,
    required String kind,
    BigInt? fee,
    required String status,
  }) = _TransactionRecord;
}

@freezed
sealed class ValueTransferRecord with _$ValueTransferRecord {
  const factory ValueTransferRecord({
    required String txid,
    required int height,
    required BigInt timestamp,
    required BigInt value,
    required String kind,
    BigInt? fee,
    String? recipientAddress,
    String? poolReceived,
    required List<String> memos,
    required String status,
  }) = _ValueTransferRecord;
}

@freezed
sealed class WalletBalance with _$WalletBalance {
  const factory WalletBalance({
    required BigInt transparent,
    required BigInt sapling,
    required BigInt orchard,
    required BigInt unconfirmedSapling,
    required BigInt unconfirmedOrchard,
    required BigInt unconfirmedTransparent,
    required BigInt totalTransparent,
    required BigInt totalSapling,
    required BigInt totalOrchard,
  }) = _WalletBalance;
}
