// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'wallet.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `legacy_err`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `from`, `from`

Future<String> createWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required int chainHeight}) =>
    RustLib.instance.api.crateApiWalletCreateWallet(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        chainHeight: chainHeight);

Future<void> restoreFromSeed(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String seedPhrase,
        required int birthday}) =>
    RustLib.instance.api.crateApiWalletRestoreFromSeed(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        seedPhrase: seedPhrase,
        birthday: birthday);

Future<void> restoreFromUfvk(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType,
        required String ufvk,
        required int birthday}) =>
    RustLib.instance.api.crateApiWalletRestoreFromUfvk(
        dataDir: dataDir,
        serverUrl: serverUrl,
        chainType: chainType,
        ufvk: ufvk,
        birthday: birthday);

Future<void> openWallet(
        {required String dataDir,
        required String serverUrl,
        required ChainType chainType}) =>
    RustLib.instance.api.crateApiWalletOpenWallet(
        dataDir: dataDir, serverUrl: serverUrl, chainType: chainType);

Future<void> closeWallet() => RustLib.instance.api.crateApiWalletCloseWallet();

Future<SyncResultInfo> syncWallet() =>
    RustLib.instance.api.crateApiWalletSyncWallet();

Future<void> startSync() => RustLib.instance.api.crateApiWalletStartSync();

Future<void> pauseSync() => RustLib.instance.api.crateApiWalletPauseSync();

Future<void> resumeSync() => RustLib.instance.api.crateApiWalletResumeSync();

Future<void> stopSync() => RustLib.instance.api.crateApiWalletStopSync();

Future<SyncResultInfo> rescanWallet() =>
    RustLib.instance.api.crateApiWalletRescanWallet();

Future<SyncStatusInfo> getSyncStatus() =>
    RustLib.instance.api.crateApiWalletGetSyncStatus();

Future<WalletBalance> getWalletBalance() =>
    RustLib.instance.api.crateApiWalletGetWalletBalance();

Future<List<AddressInfo>> getAddresses() =>
    RustLib.instance.api.crateApiWalletGetAddresses();

Future<List<String>> getTransparentAddresses() =>
    RustLib.instance.api.crateApiWalletGetTransparentAddresses();

Future<List<TransactionRecord>> getTransactions() =>
    RustLib.instance.api.crateApiWalletGetTransactions();

Future<List<ValueTransferRecord>> getValueTransfers() =>
    RustLib.instance.api.crateApiWalletGetValueTransfers();

Future<List<ValueTransferRecord>> getMessages({String? filter}) =>
    RustLib.instance.api.crateApiWalletGetMessages(filter: filter);

Future<String> sendPayment({required List<PaymentRecipient> recipients}) =>
    RustLib.instance.api.crateApiWalletSendPayment(recipients: recipients);

Future<String> shieldFunds() =>
    RustLib.instance.api.crateApiWalletShieldFunds();

Future<AddressValidation> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiWalletValidateAddress(address: address);

Future<bool> validateSeed({required String seed}) =>
    RustLib.instance.api.crateApiWalletValidateSeed(seed: seed);

Future<String> getServerInfo() =>
    RustLib.instance.api.crateApiWalletGetServerInfo();

Future<void> setServer({required String serverUrl}) =>
    RustLib.instance.api.crateApiWalletSetServer(serverUrl: serverUrl);

Future<String?> getSeedPhrase() =>
    RustLib.instance.api.crateApiWalletGetSeedPhrase();

Future<int> getBirthday() => RustLib.instance.api.crateApiWalletGetBirthday();

Future<int> getWalletSyncedHeight() =>
    RustLib.instance.api.crateApiWalletGetWalletSyncedHeight();

Future<String?> exportUfvk() => RustLib.instance.api.crateApiWalletExportUfvk();

Future<bool> hasSpendingKey() =>
    RustLib.instance.api.crateApiWalletHasSpendingKey();

Future<int> createAccount() =>
    RustLib.instance.api.crateApiWalletCreateAccount();

Future<int> getAccountCount() =>
    RustLib.instance.api.crateApiWalletGetAccountCount();

Future<WalletBalance> getAccountBalance({required int accountIndex}) =>
    RustLib.instance.api
        .crateApiWalletGetAccountBalance(accountIndex: accountIndex);

Future<String> sendFromAccount(
        {required int accountIndex,
        required List<PaymentRecipient> recipients}) =>
    RustLib.instance.api.crateApiWalletSendFromAccount(
        accountIndex: accountIndex, recipients: recipients);

Future<String> shieldAccount({required int accountIndex}) =>
    RustLib.instance.api
        .crateApiWalletShieldAccount(accountIndex: accountIndex);

Future<String> generateDiversifiedAddress(
        {required int accountIndex,
        required bool includeOrchard,
        required bool includeSapling}) =>
    RustLib.instance.api.crateApiWalletGenerateDiversifiedAddress(
        accountIndex: accountIndex,
        includeOrchard: includeOrchard,
        includeSapling: includeSapling);

Future<List<PaymentRecipient>> parsePaymentUri({required String uri}) =>
    RustLib.instance.api.crateApiWalletParsePaymentUri(uri: uri);

Future<String> buildPaymentUri(
        {required String address, required BigInt amount, String? memo}) =>
    RustLib.instance.api.crateApiWalletBuildPaymentUri(
        address: address, amount: amount, memo: memo);

Future<void> deleteWalletData({required String dataDir}) =>
    RustLib.instance.api.crateApiWalletDeleteWalletData(dataDir: dataDir);

Future<void> startSaveTask() =>
    RustLib.instance.api.crateApiWalletStartSaveTask();

Future<int> getLatestBlockHeight(
        {required String serverUrl, required ChainType chainType}) =>
    RustLib.instance.api.crateApiWalletGetLatestBlockHeight(
        serverUrl: serverUrl, chainType: chainType);

@freezed
sealed class AddressInfo with _$AddressInfo {
  const factory AddressInfo({
    required String address,
    required bool hasTransparent,
    required bool hasSapling,
    required bool hasOrchard,
  }) = _AddressInfo;
}

@freezed
sealed class AddressValidation with _$AddressValidation {
  const factory AddressValidation({
    required bool isValid,
    String? addressType,
  }) = _AddressValidation;
}

enum ChainType {
  mainnet,
  testnet,
  ;
}

@freezed
sealed class PaymentRecipient with _$PaymentRecipient {
  const factory PaymentRecipient({
    required String address,
    required BigInt amount,
    String? memo,
  }) = _PaymentRecipient;
}

@freezed
sealed class SyncResultInfo with _$SyncResultInfo {
  const factory SyncResultInfo({
    required int startHeight,
    required int endHeight,
    required int blocksScanned,
  }) = _SyncResultInfo;
}

@freezed
sealed class SyncStatusInfo with _$SyncStatusInfo {
  const factory SyncStatusInfo({
    required String mode,
  }) = _SyncStatusInfo;
}

@freezed
sealed class TransactionRecord with _$TransactionRecord {
  const factory TransactionRecord({
    required String txid,
    required int height,
    required BigInt timestamp,
    required PlatformInt64 value,
    required String kind,
    BigInt? fee,
    required String status,
    required BigInt rawValue,
  }) = _TransactionRecord;
}

@freezed
sealed class ValueTransferRecord with _$ValueTransferRecord {
  const factory ValueTransferRecord({
    required String txid,
    required int height,
    required BigInt timestamp,
    required BigInt value,
    required String kind,
    BigInt? fee,
    String? recipientAddress,
    String? poolReceived,
    required List<String> memos,
    required String status,
  }) = _ValueTransferRecord;
}

@freezed
sealed class WalletBalance with _$WalletBalance {
  const WalletBalance._();
  const factory WalletBalance({
    required BigInt transparent,
    required BigInt sapling,
    required BigInt orchard,
    required BigInt unconfirmedSapling,
    required BigInt unconfirmedOrchard,
    required BigInt unconfirmedTransparent,
    required BigInt totalTransparent,
    required BigInt totalSapling,
    required BigInt totalOrchard,
  }) = _WalletBalance;
  static Future<WalletBalance> default_() =>
      RustLib.instance.api.crateApiWalletWalletBalanceDefault();
}
